renegade-fi/relayer-extensions

- Cargo.toml
- compliance/compliance-api/Cargo.toml
- compliance/compliance-api/src/lib.rs
- compliance/compliance-server/Cargo.toml
- compliance/compliance-server/src/error.rs
- compliance/compliance-server/src/main.rs
- fee-sweeper/Cargo.toml
- fee-sweeper/src/indexer/index_fees.rs
- fee-sweeper/src/indexer/queries.rs
- fee-sweeper/src/relayer_client.rs
This PR adds the initial skeleton for the compliance API. This defines API types and a basic no-op API server for the compliance route.
- Define database schemas + migration
- Use db + chainlink API to assess wallet risk
- Manually tested the server
> compliance: compliance-server: Define initial compliance api

- Cargo.toml
- compliance/compliance-api/src/lib.rs
- compliance/compliance-server/Cargo.toml
- compliance/compliance-server/migrations/2024-06-28-231756_create_compliance_table/up.sql
- compliance/compliance-server/src/chainalysis_api.rs
- compliance/compliance-server/src/db.rs
- compliance/compliance-server/src/error.rs
- compliance/compliance-server/src/main.rs
- compliance/compliance-server/src/schema.rs
This PR implements the fallback to using the chainalysis API in the case that a wallet's risk assessment is not cached in the DB. If chainalysis delivers a successful risk assessment, we then insert it into our DB.
- Tested with my wallet addresses (compliant)
- Tested with a known sanctioned address (non-compliant)
> compliance: compliance-server: Fallback to chainalysis API if not cached

- .dockerignore
- Cargo.toml
- compliance/compliance-server/Cargo.toml
- compliance/compliance-server/Dockerfile
- compliance/compliance-server/src/main.rs
This PR adds a `Dockerfile` for the compliance server to deploy it on an ECS cluster. As well, I added env variable fallbacks for the secrets used to configure the compliance server. We will configure these via secrets manager.
- Built and ran the dockerfile and tested the compliance server
> compliance: compliance-server: Add Dockerfile

- Cargo.toml
- compliance/compliance-server/Cargo.toml
- funds-manager/Cargo.toml
- funds-manager/src/db/mod.rs
- funds-manager/src/error.rs
- funds-manager/src/indexer/index_fees.rs
- funds-manager/src/indexer/mod.rs
- funds-manager/src/indexer/queries.rs
- funds-manager/src/indexer/redeem_fees.rs
- funds-manager/src/main.rs
This PR refactors the `funds-manager` to use `diesel-async` which allows us to fit the funds manager endpoints into the `warp` interface. I expose two endpoints `index-fees` and `redeem-fees`.
- Move the endpoints and request types into an API crate as in other extensions
- Tested both endpoints
> funds-manager: Use `diesel-async` and add `warp` endpoints

- funds-manager/Dockerfile
- funds-manager/src/db/schema.rs
- funds-manager/src/main.rs
This PR updates the CLI in two ways:
1. Allows each config entry to be set by an environment variable. This will make it easier to deploy the `funds-manager` via terraform.
2. Removes the Arbitrum private key argument. We don't need a private key for any arbitrum client operations, so instead we use a dummy key -- the master key used in nitro dev nodes.
- Ran the funds manager with the dummy key and environment variables
> funds-manager: Use dummy key for arbitrum client

- funds-manager/funds-manager-api/Cargo.toml
- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/custody_client/deposit.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/error.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds an endpoint to fetch a deposit address for the quoters. This endpoint looks up the available account asset wallets for the quoter vault and finds the asset prefixed with the ERC20 symbol.
- Created a few assets in the Fireblocks sandbox and then queried for their deposit addresses. Checked that these were the same as reported in the console
> funds-manager: custody-client: deposit: Endpoint to fetch deposit addr

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/custody_client/deposit.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/error.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds an endpoint handler for the withdrawal path in the `funds-manager`'s custody client. This endpoint will find the correct vault and asset to withdraw from (borrowing code from the deposit flow) then initiate a withdrawal through Fireblocks.
- Authentication for custody API
- Deposited a few ERC20s into Fireblocks, withdrew into a personal wallet through the endpoint
> funds-manager: custody-client: Add withdrawal handler

- Cargo.toml
- bin/build_and_push.sh
- funds-manager/Dockerfile
- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/error.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/middleware.rs
This PR adds HMAC authentication for the server and applies it to the custody withdrawal endpoint. The HMAC key is a 32-byte array configured via the CLI. Users may disable auth, but must explicitly specify `--disable-auth` to do so, ensuring consent for unsafe operations.
- Wrote a proxy to attach HMACs and proxied requests to the server
> funds-manager: middleware: Add symmetric key auth for withdrawal

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds an API endpoint for refueling gas. We segment the vaults from which gas and quoter funds are drawn to more accurately track and allocate our custodied funds.
- Hit the endpoint to withdraw gas to a personal wallet
> funds-manager: Add gas refuel api

- funds-manager/funds-manager-api/Cargo.toml
- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/fee_indexer/fee_balances.rs
- funds-manager/funds-manager-server/src/fee_indexer/mod.rs
- funds-manager/funds-manager-server/src/fee_indexer/queries.rs
- funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
This PR adds an endpoint to fetch Renegade wallets for which we redeem fees into. This will allow an admin to view the current fee balances in the indexer and withdraw as desired.
- Tested locally against a running server
> funds-manager: fee-indexer: Add endpoint to view wallet fee balances

- funds-manager/funds-manager-api/Cargo.toml
- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/fee_indexer/fee_balances.rs
- funds-manager/funds-manager-server/src/fee_indexer/mod.rs
- funds-manager/funds-manager-server/src/fee_indexer/queries.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
This PR adds an endpoint to withdraw redeemed fees from fee collector Renegade wallets into our custody stack. This is brokered by the relayer which manages the fee collection wallets.
- Redeemed a number of fees and then withdrew them into Fireblocks
> funds-manager: fee-indexer: Allow withdrawal of fees to custody

- funds-manager/funds-manager-server/src/db/models.rs
- funds-manager/funds-manager-server/src/db/schema.rs
- funds-manager/funds-manager-server/src/fee_indexer/queries.rs
- funds-manager/migrations/2024-07-27-200942_create_hot_wallets_table/down.sql
- funds-manager/migrations/2024-07-27-200942_create_hot_wallets_table/up.sql
This PR adds a table to store metadata about hot wallets managed by the `funds-manager`. We will allocate one hot wallet per vault (which separates out funds by use case) and use it to holds funds on-chain that we do not want to deposit/withdraw from Fireblocks.
- Applied the migration, verified server functionality afterwards
> funds-manager: migrations: Add `hot_wallets` table

- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/db/mod.rs
- funds-manager/funds-manager-server/src/fee_indexer/mod.rs
- funds-manager/funds-manager-server/src/fee_indexer/queries.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR refactors the `funds-manager-server` to use a connection pool under the hood instead of a single connection. This allows multiple server workers to make progress simultaneously rather without messy dependency injection.
- Tested server functionality
> funds-manager-server: Use connection pool instead of raw connections

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/db/models.rs
- funds-manager/funds-manager-server/src/fee_indexer/fee_balances.rs
- funds-manager/funds-manager-server/src/fee_indexer/queries.rs
- funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds an endpoint to create a new hot wallet. Each hot wallet backs a singular vault for which it "caches" funds. We map hot wallets to vaults in a 1:1 manner to properly segment funds by their intended use. 
The hot wallet metadata is stored in the `FundsManager` database, and the private key is stored in AWS secrets manager.
- Created hot wallets for each of our existing vaults
> funds-manager: Add endpoint to create new hot wallets

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds an endpoint to query the token balances for hot wallets on-chain. The endpoint fetches all hot wallets and takes the desired mints as query parameters and looks them up on their ERC20 contracts.
- Tested the endpoint locally against a hot wallet I funded with a dummy erc20
> funds-manager: Add endpoint to fetch token balances for hot wallets

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/deposit.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR implements an endpoint that lets us withdraw from hot wallets into Fireblocks vaults. The endpoint takes the following steps:
1. Lookup the hot wallet in our database, find its vault
2. Lookup the vault deposit address that the specific ERC20 targets
3. Execute an ERC20 transfer to the vault address
- Tested the endpoint locally by transferring a dummy erc20 into Fireblocks
> funds-manager: custody-client: Add endpoint to withdraw to cold storage

- funds-manager/funds-manager-server/src/custody_client/deposit.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/fee_indexer/fee_balances.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR updates the deposit/withdraw target for all clients of the funds manager to target hot wallets. Movement between fireblocks and hot wallets will initially be done manually via the admin panel. All automated movements will target the hot wallets.
- Tested all deposit/withdraw endpoints after these changes
> funds-manager: Change external deposit/withdraw target to hot wallets

- funds-manager/funds-manager-server/src/custody_client/deposit.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
This PR changes the way we resolve asset IDs in the Fireblocks client. Specifically, we lookup assets directly via the `/supported-assets` API, filter them by contract address, and use the asset ID in that API response.
Previously, we were using the ERC20 symbol name to find asset IDs, which plays poorly with the testnet setup.
- Tested both the `/custody/hot-wallets/withdraw-to-hot-wallet` and `/custody/hot-wallets/transfer-to-vault` routes for functionality. These are the two routes that resolve asset IDs directly
> funds-manager: Lookup Fireblocks asset IDs via ERC20 address

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/db/models.rs
- funds-manager/funds-manager-server/src/db/schema.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/migrations/2024-08-01-021728_add_internal_wallet_id/down.sql
- funds-manager/migrations/2024-08-01-021728_add_internal_wallet_id/up.sql
This PR makes the following changes to bring the `funds-manager` into a working state with our testnet environment:
- Remove the sandbox flag on the Fireblocks client
- Add an `internal_wallet_id` mapping to the hot wallets table. Fireblocks requires that we specify whitelisted withdrawals to a wallet ID rather than its address. I manually added wallet IDs for each of the existing hot wallets
- Use a `create_transaction_peer` with `PeerType::INTERNAL_WALLET` to withdraw from Fireblocks. This allows us to control where our funds flow to via a TAP
- Tested withdrawing from fireblocks and depositing into it
> funds-manager: Add internal wallet id mapping & use internal transaction

- funds-manager/funds-manager-server/src/db/models.rs
- funds-manager/funds-manager-server/src/db/schema.rs
- funds-manager/migrations/2024-08-01-214330_add_gas_wallets_table/down.sql
- funds-manager/migrations/2024-08-01-214330_add_gas_wallets_table/up.sql
This PR adds the `gas_wallets` table to the funds manager. The funds manager will use this to track gas wallets active in the relayer cluster, allocating new relayers inactive gas wallets.
- Applied the migration
> funds-manager: migrations: Add `gas_wallets` table

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/gas_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/db/models.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds an endpoint for creating new gas wallets in the funds manager. These wallets are all marked as inactive and eligible to be allocated to a relayer upon request.
- Created a few new gas wallets
> funds-manager: custody-client: Add endpoint for creating gas wallets

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/gas_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds an endpoint for a peer to register a gas wallet assigned to them. The funds manager will then mark the wallet as active and assigned to the given peer, fetch the wallet's private key from secrets manager, and return the key to the client.
- Hit the endpoint, checked the database entries & the key
- Hit the endpoint enough times to consume all available keys, verified that I received an error
> funds-manager: custody-client: Add endpoint for registering a gas wallet

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/gas_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds a handler for the `/report-active-peers` endpoint which allows separate infrastructure to report active Renegade nodes. The `funds-manager` uses this information to mark a wallets as pending or inactive.
- Tested all flows from active -> pending -> inactive and combinations between them
> funds-manager: custody-client: Add handler for reporting active peers

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/src/custody_client/gas_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR refactors the way in which we refill gas in the `funds-manager`. Specifically, we now refill gas by looking up active gas wallets and topping off their balances directly.
- Registered a new wallet as active then refilled its gas to 0.1 ETH
> funds-manager: Refill gas to active wallets

- funds-manager/funds-manager-api/Cargo.toml
- funds-manager/funds-manager-api/src/auth.rs
- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/middleware.rs
This PR moves auth helpers to the `funds-manager-api` which allows clients to import them much easier. This way clients can share HMAC implementations with the server.
- Used these helpers to sign gas wallet registration requests in the node support bootloader
> funds-manager: funds-manager-api: Publish API auth helpers

- funds-manager/funds-manager-server/src/execution_client/error.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
- funds-manager/funds-manager-server/src/main.rs
This PR bootstraps the `ExecutionClient` and adds quote and price fetch helpers from the 0x swap API. We will have a human in the loop to begin with the quote API exposed directly. When a user accepts the quote they will send to the funds manager's swap API for execution.
- Tested both APIs via temporary unit tests in the codebase
> funds-manager: execution-client: Add quote and price helpers

- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/execution_client/error.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/helpers.rs
This PR sets up the execution flow for the `ExecutionClient` which involves:
1. Approving an ERC20 allowance for the 0x exchange proxy
2. Sending the transaction detailed by the quote received
- Tested buying $GMX with $USDC on arbitrum using my personal wallet
> funds-manager: execution-client: Add quote execution helpers

- funds-manager/funds-manager-api/src/serialization.rs
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/execution_client/error.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
This PR implements the quote fetch and execution endpoints for quoter rebalancing. In addition to the straightforward calls to the `ExecutionClient`, I also moved ERC20 approvals to the quote phase. This is necessary as the 0x API will not provide a quote unless the sell side balance is already approved.
- Tested on Arbitrum mainnet by funding the quoter wallet on mainnet from my personal wallet. Hit the endpoint to fetch and execute on a quote to buy $GMX.
> funds-manager: handlers: Handle quote fetch and execution

- Cargo.lock
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/custody_client/gas_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/fee_indexer/fee_balances.rs
- funds-manager/funds-manager-server/src/fee_indexer/index_fees.rs
- funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
This changes the funds manager to be compatible with the new key rotation changes in the relayer. Specifically, this changes the shape of requests to the relayer that now do not necessarily send the whole keychain. As well, the auth between the client and the relayer now uses the wallet's symmetric key.
> funds-manager: Ingest API changes from key rotation

- funds-manager/funds-manager-api/src/types/quoters.rs
This PR adds the [`estimatedGas` field](https://0x.org/docs/1.0/0x-swap-api/api-references/get-swap-v1-quote#response) to the subset of Matcha `/swap/v1/quote` response fields captured by the `ExecutionQuote` struct.
This is purely for convenience, we would like to be able to view the all-in estimated gas cost when considering an execution.
> funds-manager: api: types: quoters: add `estimated_gas` field to `ExecutionQuote`

- Cargo.lock
- price-reporter/src/http_server/routes.rs
- price-reporter/src/main.rs
- price-reporter/src/utils.rs
- price-reporter/src/ws_server.rs
This PR makes a few changes to the price reporter:
- Changes the underlying synchronization primitive to a `Watch` which 1. streams immediately, and 2. more directly captures the semantics of the price reporter.
- Using a watch means that a websocket and http request both _instantly_ get a price
- Initialize default pair streams on startup
- Do not remove a stream once clients disconnect
- Tested all websocket pairs, verified that they began streaming instantly
> price-reporter: Make misc reliability improvements

- price-reporter/src/ws_server.rs
This PR makes two changes:
1. We refactor the `price_stream_task` into a retry wrapper that calls `manage_connection`. This captures a broader set of errors that may be retried, including error sending a keepalive on a closed connection. Looking at our logs, this makes up the majority of server failures
2. Adds logging for the case in which re-establishing a connection fails
- Ran the price reporter locally and simulated a failure, verified that the recovery logic worked as expected
> price-reporter: ws-server: Retry connection on send failure

- Cargo.lock
- auth-server/Cargo.toml
- auth-server/diesel.toml
- auth-server/migrations/00000000000000_diesel_initial_setup/down.sql
- auth-server/migrations/00000000000000_diesel_initial_setup/up.sql
- auth-server/migrations/2024-10-21-205301_add_api_keys_table/down.sql
- auth-server/migrations/2024-10-21-205301_add_api_keys_table/up.sql
- auth-server/src/main.rs
- auth-server/src/schema.rs
This PR initializes the db migration setup for the auth server as well and creates the API keys table through the first migration. This table stores both the API key IDs and encrypted API secrets.
- Applied the migration
> auth-server: Initialze DB migrations and api keys table

- Cargo.lock
- auth-server/Cargo.toml
- auth-server/src/main.rs
- auth-server/src/server/handle_proxy.rs
- auth-server/src/server/mod.rs
This PR builds out the initial server functionality and endpoint handlers. Specifically this PR:
- Build the `Server` type to server as a dependency container
- Adds a database connection pool to the configured DB
- Moves endpoint handlers into the `Server` type
- Tested the proxy fallback with a locally running relayer on unauthenticated endpoints (e.g. `/v0/network`)
> auth-server: server: Build `Server` type as dependency container

- Cargo.lock
- auth/auth-server-api/src/lib.rs
- auth/auth-server/Cargo.toml
- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/models.rs
- auth/auth-server/src/server/handle_proxy.rs
- auth/auth-server/src/server/queries.rs
This PR uses the allocated API keys to authenticate an proxy request to the auth server. Specifically the flow is:
- Retrieve the user's encrypted API secret from the database using their API key as a key
- Decrypt the API secret using the server's decryption key
- Check an expiring HMAC on the request using the decrypted API secret
- If this passes, forward the request to the relayer
- Check the path to ensure it's an allowed path
- Attach admin auth to the request
- Built a client and allocated an API key for the client, verified that the client was able to call relayer methods through the auth server
> auth-server: Use api keys to authenticate proxy requests

- Cargo.lock
- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/api_auth.rs
- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/queries.rs
This PR uses the relayer admin key to authorize proxied requests from the auth server. I also setup a non-generic router to limit the routes that the proxy may be used to access.
- Generated and submitted an atomic match through the auth API with an API key
> auth-server: Use admin auth to proxy relayer requests

- Cargo.lock
- auth/auth-server/Cargo.toml
- auth/auth-server/src/models.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/queries.rs
This PR adds a local API key cache to the auth server. This removes the DB query from the critical path for a match bundle. Note that for now the cache is in-memory so we'll need to run the auth-server single node. If we decide to move to multi-node we can move the cache to a memcached instance, but for now this is simple.
- Tested all cache insert and invalidation paths
> auth-server: Add local api key cache

- auth/Dockerfile
- auth/auth-server/src/main.rs
This PR fixes the auth server's Dockerfile after the auth server was refactored into two crates, one containing the API.
- Deployed to testnet
> auth-server: Fix dockerfile after crate refactor

- auth/auth-server/src/server/api_auth.rs
This PR logs the entity descriptor for each authorized request brokered by the auth server.
> auth-server: api-auth: Log key description for authorized request

- Cargo.lock
- Cargo.toml
- price-reporter/src/errors.rs
- price-reporter/src/http_server.rs
- price-reporter/src/http_server/routes.rs
- price-reporter/src/main.rs
- price-reporter/src/utils.rs
- price-reporter/src/ws_server.rs
This PR adds an authenticated route to the price reporter for refreshing the token mapping. The authentication scheme is inherited from the relayer, and in accordance with this the price reporter now accepts an HMAC key in its configuration.
After the token mapping is refreshed, price streams are reinitialized. This is a no-op for existing price streams but will start streams for any newly-added tokens. Note that in the case of tokens being _removed_ from the mapping, the price streams will not be closed - but practically this is not a concern.
This was tested locally, with authentication disabled and using a local token mapping file instead of modifying the actual repo. This will be tested end-to-end in testnet shortly.
> price-reporter: routes: add admin token mapping refresh route

- Cargo.lock
- auth/auth-server/Cargo.toml
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR records metrics on external match settlement. 
Tested locally against locally running auth server and Datadog agent. Example dashboard from this data [here](https://us5.datadoghq.com/dashboard/6j9-i8d-xdq?fromUser=true&refresh_mode=paused&from_ts=1733870660790&to_ts=1733899576032&live=false).
Need to test in testnet stack.
> auth server: record settlement metrics

- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR adds metric tags to allow for richer queries in DD. Specifically, we want to 
- correlate different components of a request together (order, bundle, settlement)
- indicate base asset on quote volume metrics to group by base asset
Tested against locally running auth server and Datadog agent.
> auth server: add request-level tag

- auth/Dockerfile
This PR removes the `--datadog-logging` flag from the Dockerfile since the flag name has been changed and is now defined in Terraform.
> auth-server: remove unnecessary flag in Dockerfile

- auth/auth-server/src/telemetry/helpers.rs
This PR fixes the quote amount calculation that was previously using the price value that was not decimal corrected.
> auth-server: fix quote amount calculation

- auth/auth-server/src/telemetry/helpers.rs
This PR fixes an issue where the `quote_amount` calculation would lose precision when casting from `f64` to `u128`, especially for base tokens with 18 decimals.
Relies on https://github.com/renegade-fi/renegade/pull/862
> auth-server: use get-quote-amount helper

- Cargo.lock
- Cargo.toml
- auth/auth-server/Cargo.toml
This PR updates relayer dependencies to ingest quote amount calculation changes and ensures the auth server uses the workspace relayer dependencies.
> auth-server: update deps, use workspace imports

- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR adds a tag that indicates data was recorded post decimal correct fix.
> auth-server: tag metrics as post-fix

- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR adds the post fix tag to the request counter metric. Also changes the tag name so that data is aligned when filtered.
> auth-server: tag counter matric as post fix

- Cargo.lock
- auth/auth-server/Cargo.toml
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/rate_limiter.rs
- auth/auth-server/src/telemetry/helpers.rs
This PR implements bundle rate limits for the auth server. Specifically, we rate limit the number of inflight, unsettled bundles per client. So, a client may accrue new API tokens by either:
- Waiting for their token bucket to refill
- Settling a match
> auth-server: server: rate-limiter: Implement bundle rate limits

- auth/auth-server/src/main.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/rate_limiter.rs
This PR accepts the bundle rate limit as a CLI argument
> auth-server: rate-limiter: Configure rate limit from command line

- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR records fill ratios of quote requests and external match requests (to be deprecated) for display as histograms on a Datadog dashboard. Also records number of quote requests per key.
> auth-server: record fill ratio metrics

- auth/auth-server/src/server/handle_external_match.rs
This PR fixes a bug where the price of a quote was doubly decimal corrected, resulting in incorrect fill ratio metrics. The post-decimal-fix tag will be used to filter out any incorrect metrics in DD.
> auth-server: fix repeated decimal correction

- auth/auth-server/src/server/rate_limiter.rs
This PR fixes a bug wherein the token buckets were not being refilled properly after the timeout period.
> auth: auth-server: rate-limiter: Properly refill token bucket

- auth/auth-server/src/server/mod.rs
This PR logs a warning when a request is throttled by the auth server rate limiter
> auth-server: Add warning log for rate limits

- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
- auth/auth-server/src/telemetry/mod.rs
- auth/auth-server/src/telemetry/quote_comparison.rs
- auth/auth-server/src/telemetry/sources/mod.rs
This PR adds quote comparison metrics to track how our prices compare to other sources. It introduces:
- A new QuoteComparisonMetrics struct that records price differences in basis points
- Mock quote sources (Binance, Coinbase) that generate random prices within 2% of our quotes
The metrics will help us monitor our price competitiveness vs other venues. Real quote sources will be added in future PRs - this initial implementation with mock sources allows us to test the metrics infrastructure and finalize the tags/fields needed for an initial Datadog quote comparison widget.
> auth-server: record quote comparison metrics

- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/mod.rs
This PR implements a helper to sample metrics.
According to our Usage page in Datadog, quote metrics are recorded ~25k/per hour. This is resulting in widgets erroring with `Query Response Size Exceeded` and increased costs.
In a future PR, we can migrate metrics for `num_external_match_quote_requests` to be log-based if we don't want to sample those metrics but still want to save on costs.
> auth-server: sample quote endpoint metrics

- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/quote_comparison/handler.rs
- auth/auth-server/src/telemetry/quote_comparison/mod.rs
- auth/auth-server/src/telemetry/sources/mod.rs
- auth/auth-server/src/telemetry/sources/odos/mod.rs
- auth/auth-server/src/telemetry/sources/odos/types.rs
This PR makes better use of the `QuoteComparison` and `QuoteSource` structs to make metric recording code more readable and extensible. Future PRs will build upon these changes to colocate helpers to get price net of fees, price net of gas, etc.
> auth-server: organize quote comparison structs

- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/rate_limiter.rs
- auth/auth-server/src/telemetry/quote_comparison/handler.rs
- auth/auth-server/src/telemetry/quote_comparison/price_reporter_client.rs
- auth/auth-server/src/telemetry/sources/http_utils.rs
- auth/auth-server/src/telemetry/sources/mod.rs
- auth/auth-server/src/telemetry/sources/odos/client.rs
- auth/auth-server/src/telemetry/sources/odos/error.rs
- auth/auth-server/src/telemetry/sources/odos/mod.rs
- auth/auth-server/src/telemetry/sources/odos/types.rs
This PR adds rate limits to the quote endpoint for external matches, starting at 100 requests/min.
I also took care of some clippy lints around missing docs.
> auth-server: rate-limiter: Rate limit quote endpoint

- Cargo.lock
- auth/auth-server/Cargo.toml
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
- auth/auth-server/src/telemetry/quote_comparison/handler.rs
- auth/auth-server/src/telemetry/quote_comparison/mod.rs
- auth/auth-server/src/telemetry/sources/mod.rs
- auth/auth-server/src/telemetry/sources/odos/mod.rs
This PR takes into account fees when recording quote comparison metrics. We do so by calculating the fee take amount and storing it in the `QuoteResponse` struct.
> auth-server: add output net of fees

- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
- auth/auth-server/src/telemetry/quote_comparison/handler.rs
- auth/auth-server/src/telemetry/quote_comparison/mod.rs
- auth/auth-server/src/telemetry/sources/mod.rs
This PR records metrics net of both gas costs and fees.
> auth-server: record metrics for output net of gas and fees

- price-reporter/src/http_server.rs
- price-reporter/src/http_server/routes.rs
- price-reporter/src/main.rs
- price-reporter/src/utils.rs
This PR adds a `DISABLED_EXCHANGES` environment variable to the price reporter config which can be used to disable the initialization of price streams for the specified exchanges. This can be useful when the exchange APIs themselves are experiencing downtime, which would force downtime upon our own price reporter due to the self-shutdown logic invoked when reconnection retries are exhausted.
> price-reporter: add disabled exchanges config option

- funds-manager/funds-manager-api/src/types/gas.rs
- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/server.rs
This PR adds the `/custody/gas/refill-gas-sponsor` route to the funds manager, used to refill the gas sponsor's ETH balance. This is necessary, i.e. the `/custody/gas/withdraw-gas` route can't be used, since the `receiveEth` method on the gas sponsor must be invoked.
This was tested by running a local funds manager against the testnet stack & invoking the endpoint.
> funds-manager: custody_client: gas_sponsor: add gas sponsor refill route

- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
- auth/auth-server/src/telemetry/sources/mod.rs
- funds-manager/funds-manager-api/src/types/gas.rs
- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/server.rs
This PR adds the recording of a metric tracking the $ value spent in gas sponsorship for settled matches.
The second commit in this PR is purely cosmetic and moves around various gas sponsorship helpers into a single module for cleanliness. Only the first commit needs to be reviewed for soundness.
> auth-server: server: handle_external_match: add gas sponsorship metrics

- Cargo.lock
- auth/auth-server-api/Cargo.toml
- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
- auth/auth-server/src/telemetry/quote_comparison/handler.rs
- auth/auth-server/src/telemetry/quote_comparison/price_reporter_client.rs
- auth/auth-server/src/telemetry/sources/http_utils.rs
- auth/auth-server/src/telemetry/sources/mod.rs
- funds-manager/funds-manager-api/src/types/gas.rs
- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/server.rs
This PR integrates usage of the gas sponsorship rate limiter into the external match paths in the auth server. We do this by checking the rate limit when a request for a sponsored match comes in, and consuming the user's gas sponsorship budget if they settle the bundle by fetching the ETH price and the amount of gas sponsored for the request.
> auth-server: server: handel_external_match: use gas sponsorship rate limiter

- .gitignore
- Cargo.lock
- auth/auth-server-api/src/lib.rs
- auth/auth-server/Cargo.toml
- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/sources/mod.rs
This PR adds the ability to redirect the transaction in assembled quotes to a configured gas sponsorship context by specifying the `use_gas_sponsorship` (and optionally `refund_address`) query params.
I tested this by invoking external matches on a locally-running auth server pointed against the testnet stack, trying buys/sells on both normal ERC20s and native ETH. I asserted that the gas sponsorship contract was being invoked as expected and refunding w/in 15k gas worth of ETH to the desired address. I tested w/ and w/o a refund address set, as well.
- Add gas sponsorship to the direct match bundle route
- Gas sponsorship rate limiting
- Telemetry/monitoring around gas sponsorship
> auth-server: handle_external_match: mutate calldata for gas sponsorship

- auth/auth-server/src/server/handle_external_match/gas_sponsorship.rs
This PR adds a log in the case that a sponsored match event is not found
> auth: server: handle_external_match: gas_sponsorship: log missing sponsorship event

- auth/auth-server/src/error.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/quote_comparison/handler.rs
- auth/auth-server/src/telemetry/sources/mod.rs
- auth/auth-server/src/telemetry/sources/odos/error.rs
- auth/auth-server/src/telemetry/sources/odos/mod.rs
This PR ensures that we  gracefully handle errors in quote comparison recording so that we don't panic the thread.
> auth-server: telemetry: gracefully handle quote comparison errors

- Cargo.lock
- auth/auth-server/src/server/api_auth.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
- price-reporter/src/http_server/routes.rs
- price-reporter/src/utils.rs
This PR updates dependencies and fixes import paths for `HmacKey`.
> Cargo.lock: Update lockfile to fetch latest relayer deps

- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
This PR tweaks the external match & quote assembly endpoints to only redirect a bundle through the gas sponsor contract if sponsorship has been explicitly requested by the client. In this case, the bundle will be directed to the gas sponsor regardless of whether the user is rate-limited. This way, users that opt into sponsorship can always expect the same contract address to be used, users that opt out can continue expecting the darkpool to be used and don't have to do new token approvals.
Additionally, this change results in the API response type only including the `is_sponsored` field if sponsorship was explicitly requested. This way, users opting out of sponsorship can expect no changes to the response type.
> auth: server: handle_external_match: gas_sponsorship: only redirect tx through gas sponsor when requested

- Cargo.lock
- Cargo.toml
- price-reporter/Cargo.toml
- price-reporter/src/errors.rs
- price-reporter/src/main.rs
- price-reporter/src/utils.rs
This PR uses the new coinbase auth method in the price reporter.
> price-reporter: utils: Use new coinbase connection args

- .gitignore
- auth/auth-server/src/server/handle_external_match/gas_sponsorship.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
This PR ensures that we await a nullifier spend event on the correct selectors, and that we are able to deserialize either a sponsored or unsponsored match response when handling the bundle for telemetry.
Tested by running a local auth server against both the testnet and mainnet stacks
> auth-server: telemetry: await nullifier spend on correct selectors

- Cargo.lock
- auth/auth-server-api/src/lib.rs
- auth/auth-server/Cargo.toml
- auth/auth-server/src/error.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
This PR implements the necessary changes to invoke external matches sponsored in-kind through the gas sponsor. Primarily, this is composed of an additional query parameter `refund_native_eth` - which defaults to `false`, implying that in-kind gas sponsorship is the default - and the logic for computing a conversion rate for in-kind sponsorship.
> auth-server: handle_external_match: gas_sponsorship: compute conversion rate

- auth/auth-server/src/server/handle_external_match/gas_sponsorship.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/telemetry/helpers.rs
This PR updates the way in which we record the value of gas sponsorship, both for rate limiting and telemetry, to account for in-kind sponsorship.
> auth-server: handle_external_match, telemetry: record in-kind gas sponsorship value

- auth/auth-server/src/error.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/gas_estimation.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/telemetry/sources/mod.rs
This PR scaffolds the `gas_estimation` module and implements the core gas estimation logic, which for the moment is very simple. We use a constant estimate of both the amount of L2 gas needed to execute the external match, and the calldata size in bytes. We use these values along with a real-time sampling of the L2 basefee and estimated amount of L1 gas used from the [`NodeInterface`](https://docs.arbitrum.io/build-decentralized-apps/nodeinterface/overview) precompile to compute an estimated gas cost according to the instructions [here](https://docs.arbitrum.io/build-decentralized-apps/how-to-estimate-gas).
This functionality is not yet used so clippy lints are expected.
> auth-server: gas_sponsorship: gas_estimation: core gas estimation logic

- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/gas_estimation/gas_cost_sampler.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
This PR lays the groundwork for sponsoring gas using exact token amounts. Namely, the changes here are:
1. Preempt contract interface changes: we now expect the contracts to directly receive a `refund_amount` for gas sponsorship
2. Use the new `gas_estimation` module combined with the existing conversion logic to compute the refund amount in the appropriate token
3. Configure abstraction boundaries to lift computation of the refund amount out of the calldata construction code path. This will be necessary for computing the amount during the "quote" stage of the "quote-assemble" flow, the changes for which will come in a later PR
> auth-server: gas_sponsorship: use exact refund amount

- auth/auth-server/src/server/gas_estimation/constants.rs
- auth/auth-server/src/server/gas_estimation/gas_cost_sampler.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
This PR tweaks the constants used in gas estimation to be more accurate. We tune down the `ESTIMATED_L2_GAS` to 3.6M, and use `ESTIMATED_CALLDATA_SIZE_BYTES * 0.75` as an approximation of the compressibility of our calldata. We also make a couple misc tweaks: skipping fetching a conversion rate for WETH, and adding some useful tags to quote / bundle logs.
> auth-server: gas_estimation: make gas estimation constants more accurate

- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/api_auth.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/contract_interaction.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/refund_calculation.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
This PR scaffolds the process by which gas sponsorship will be applied to requested quotes. We update the returned quote if necessary, adding the gas sponsorship info to the response object. This is useful not only to clients, but also so that we can reconstruct the original relayer-signed quote during assembly. For this reason we sign the sponsorship info in the response.
In this PR, we also move around a bit of code to make for better-packaged helpers. This is in anticipation of the assembly endpoint using the gas sponsorship info from the quote. It's worth noting that, if we want to maintain perfect backwards compatibility, we would still need to support requesting gas sponsorship at the assembly step. However this will be handled as an edge case until it is deprecated, and the …
> auth-server: handle_external_match, gas_sponsorship: update external quote w/ sponsorship info

- auth/auth-server-api/src/lib.rs
- auth/auth-server/Cargo.toml
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/mod.rs
This PR tweaks the sponsored API request/response types to manually flatten the fields of the relayer API types they wrap. This is necessary because `u128`s are not supported where `#[serde(flatten)]` is used: https://github.com/serde-rs/json/issues/625.
Additionally, when proxying the quote assembly request to the relayer, we need to ensure that the `content-length` header is appropriately updated so that the relayer can properly deserialize the request body.
In both of these test cases, I asserted that the requested quote had the price and receive amount appropriately updated, and that assembled/settled bundle matched up with the expected receive amount.
This implicitly verified that "reversing" the effects of sponsorship on the sponsored quote so that the assembly request can be …
> auth-server-api: manually flatten nested API types

- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/contract_interaction.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/refund_calculation.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR ensures that the match bundles resulting from sponsored quotes also have their traded amounts updated to reflect gas sponsorship, when appropriate (i.e., when the refund is in-kind and goes to the receiver). We also make some updates to recorded telemetry. Note that telemetry will be recorded using post-sponsorship amounts / prices, this is a more accurate view anyway.
> auth-server: handle_external_match: gas_sponsorship: update match bundle w/ refund amount

- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/refund_calculation.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
This PR sets appropriate default parameters for gas sponsorship. Concretely, we have to disable in-kind gas sponsorship by default in the qutoe request endpoint for backwards compatibility with SDKs. Additionally, we deprecate the `use_gas_sponsorship` query parameter in favor of `omit_gas_sponsorship`, for more intuitive `false` defaults. This is a breaking change - un-updated clients that try to explicitly disable gas sponsorship with `use_gas_sponsorship=false` will have this parameter ignored. However, un-updated clients will enjoy gas sponsorship being enabled by default for direct matches.
> auth-server: handle_external_match: new gas sponsorship defaults

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR modifies the `/get-execution-quote` endpoint to essentially proxy requests to the LiFi `/quote` endpoint. This is because we don't need to any type validation of query params and/or response bodies as we can just forward requests, responses, errors. 
In a future PR, we will sign the quote for verification in the `/execute-swap` endpoint.
This requires moving the erc20 approval into the `/execute-swap` route.
> funds manager server: modifications for switching execution venues

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds a `/custody/quoters/withdraw-to-hyperliquid` endpoint, used to bridge funds into Hyperliquid. We do this from the quoter hot wallet to simplify custody management.
This requires first transferring USDC from the quoter hot wallet to the _same keypair we use for Hyperliquid, on Arbitrum_, before then transferring from that keypair to the bridge contract. This is necessary as the funds will be credited to the same address (on Hyperliquid) that sent them to the Arbitrum bridge.
This was tested against testnet, where I confirmed that funds were received in Hyperliquid.
Note, that when testing this functionality, we need to use Hyperliquid's [dummy USDC token](https://sepolia.arbiscan.io/address/0x1baabb04529d43a73232b713c0fe471f7c7334d5).
> funds-manager: custody_client: implement withdrawal to hyperliquid

- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR adds a `num_unsuccessful_relayer_requests` metric, a counter which is incremented each time a non-200 status code is returned by the relayer for quote, assembly, or direct match requests. The metric is tagged with the requesting entity, the status code, and the path which was invoked.
> auth-server: handle_external_match, telemetry: record unsuccessful relayer req metric

- Cargo.lock
- funds-manager/funds-manager-api/Cargo.toml
- funds-manager/funds-manager-api/src/auth.rs
- funds-manager/funds-manager-api/src/types/mod.rs
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-api/src/types/venue.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/middleware.rs
- funds-manager/funds-manager-server/src/server.rs
This PR ensures only quotes that originated from the funds manager are executed. I do so by signing the quote and including this when returning quotes to clients. This signature is then verified when clients attempt to execute a quote.
We use a separate HMAC key for signing quotes than authenticating API requests. It will also be stored in ASM.
> funds-manager-api, server: generate and verify quote signature

- Cargo.lock
- auth/auth-server/Cargo.toml
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/redis_queries.rs
This PR implements the reading/writing of `GasSponsorshipInfo` structs to/from Redis, along with the associated helper for deriving a UUID from a signed quote by hashing its signature. I've confirmed that AWS ElastiCache, which we'll use to host a managed Redis cluster, supports the Redis JSON commands.
I tested this w/ a local Redis stack & auth server, confirming that we can read/write a `GasSponsorshipInfo` struct to/from Redis as expected.
> auth-server: redis_queries: r/w gas sponsorship info to/from redis

- Cargo.lock
- auth/auth-server/Cargo.toml
- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/redis_queries.rs
This PR introduces a Redis client to the auth server, which will be used to cache gas sponsorship info for automatic sponsorship.
Two deliberate omissions worth mentioning:
1. We avoid using a connection pool such as `bb8`, as it is [recommended](https://github.com/redis-rs/redis-rs/issues/1319#issuecomment-2343783281) to use the single, shareable connection managed by the `ConnectionManager` instead. This lowers the overhead of establishing multiple connections, and handles automatic reconnection
2. We don't use any [client-side caching](https://docs.rs/redis/latest/redis/caching/index.html). In general we expect each entry to be written to once and read once, so it's not worth the complexity.
This was tested by running a local (unauthenticated) Redis server, and exposing a testing …
> auth-server: connect to redis

- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/refund_calculation.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/redis_queries.rs
This PR updates the quote request & assembly handlers to cache the calculated gas sponsorship info in Redis, and use that cached value, respectively.
> auth-server: handle_external_match: use cached gas sponsorship info

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-api/src/types/venue.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
This PR adds and uses the gas limit field to the `ExecutionQuote` fetched from the execution venue. This fixes transactions reverting due to `out of gas`.
> funds-manager: execution_client: use provided estimated gas limit

- funds-manager/funds-manager-server/src/execution_client/swap.rs
This PR checks the transaction receipt status before returning, erroring if it reverted. This fixes an issue where reverted transactions would be logged as successful because we received the receipt, but with status = failed.
> funds-manager: quote: validate tx receipt status

- price-reporter/src/http_server/routes.rs
This PR adds headers to the `/price` Response to ensure cross-origin requests are allowed to hit it. This enables frontends to fetch prices over HTTP.
> price-reporter: http_server: add cors headers to /price endpoint

- auth/auth-server/src/server/handle_external_match/mod.rs
This PR enables default in-kind sponsorship for quote requests, now that it isn't necessary for SDKs to be updated to apply sponsorship correctly.
> auth-server: handle_external_match: default in-kind sponsored quotes

- auth/auth-server/src/main.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
This PR updates the auth server startup logic to fetch & set the external match fees. This is sometimes necessary when calculating the base/quote amounts in an external order, particularly when a client specifies an exact base/quote amount in the request.
Additionally, we reorganize some of the startup logic, and add a timeout for connecting to the Redis client (the auth server would otherwise hang indefinitely).
> auth-server: server: set external match fees on startup

- Cargo.lock
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/metrics/labels.rs
- funds-manager/funds-manager-server/src/metrics/mod.rs
- funds-manager/funds-manager-server/src/server.rs
This PR adds metric recording for costs incurred when executing a swap. We record three new metrics:
- `swap_execution_cost`
- `swap_notional_volume`
- `swap_relative_spread`
which will be used to create a dashboard that tracks our average execution cost. We tag each metric with `asset`, `side`, and `hash` so we can track execution costs and spreads by asset and directions.
Tested locally that metrics are recorded, are correctly formatted, and can be accessed through the Datadog UI.
> funds-manager: server: add metrics recorder for swap costs

- auth/auth-server/src/main.rs
- auth/auth-server/src/server/gas_estimation/gas_cost_sampler.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/rate_limiter/gas_sponsorship_rate_limiter.rs
- auth/auth-server/src/server/rate_limiter/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR tags the `gas_sponsorship_value` metric with additional metadata helpful for monitoring our gas sponsorship expenditure, namely:
- The remaining value in the user's rate limit bucket
- The remaining time in the user's rate limit bucket
- The asset through which gas was refunded
- The refund amount, in whole units of the asset
- The L1 & L2 gas prices at the time of the expenditure being recorded
- There is some drift in gas prices between when a bundle's refund amount was calculated, and when we sample gas prices to record expenditure, but this is still very useful
Additionally, we drop the default value of the gas sponsorship rate limit to $25.
> auth-server: gas_estimation, rate_limiter: addnl sponsorship expenditure metadata

- auth/auth-server/src/server/price_reporter_client/error.rs
- auth/auth-server/src/server/price_reporter_client/mod.rs
- auth/auth-server/src/server/price_reporter_client/price_stream.rs
This PR upgrades the auth server `PriceReporterClient`'s price stream from streaming a single price (ETH) to streaming prices for an arbitrary number of token mints passed in when the stream is started up.
This will be used in respecting exact output amounts for in-kind sponsored quotes, where we will have to compute refund amounts (and thus know the price of the buy-side token) before we have any match result from the relayer from which we can infer a price. We opt to stream prices for this so as to not burden the critical path of requesting a quote with the latency of an HTTP request to the price reporter.
We continue to opt for a bespoke implementation of the price reporter streaming client, as opposed to the one defined in the relayer, as the latter has a lot of path dependence on the …
> auth-server: price_reporter_client: stream prices for all tokens

- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/refund_calculation.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/price_reporter_client/error.rs
- auth/auth-server/src/server/price_reporter_client/mod.rs
This PR updates the quote request endpoint to properly respect requested exact output amounts for sponsored quotes. Namely, this means that when a quote is requested with an exact amount of the output token specified, _and_ in-kind gas sponsorship directed to the receiver is applied, we subtract the refund amount from the exact output amount before sending the quote request to the relayer.
As a result, the relayer will produce a _smaller_ quote which will bear the exact output amount requested when the refund is issued alongside it. We ensure that the exact output amount in the quote response sent to the user matches what they originally requested.
This requires us to compute a refund amount _prior_ to receiving a match result/quote from the relayer, which can be done efficiently by …
> auth-server: handle_external_match: update quote request to account for sponsorship

- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/refund_calculation.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
This PR ensures that exact output amounts are properly respected both when assembling quotes, and executing direct matches.
Concretely, this entails ensuring that the refund amount is subtracted from the order (or updated order) being assembled / matched directly.
This is necessary to ensure the bundle served by the relayer matches a smaller order size such that the exact output amount is met post-refund, and in the case of assembly, also ensures that the quote matches what was signed by the relayer.
Testing is deferred to the following PR, as this one resulted in a fair bit of cleanup due to generating gas sponsorship data before proxying any requests to the relayer, and I didn't want this review to snowball
> auth-server: handle_external_match: sponsored exact output in assembly & direct match

- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
This PR ensures that we only sponsor gas for orders above a given quote volume, which is configurable via the CLI / env vars and defaults to 10 USDC.
We also remove now-unnecessary backwards compatibility logic for requesting sponsorship at the assembly stage.
> auth-server: handle_external_match: gas_sponsorship: sponsor orders above set size

- Cargo.lock
- price-reporter/src/http_server/routes.rs
- price-reporter/src/utils.rs
- price-reporter/src/ws_server.rs
This PR adds support for the `Renegade` exchange in the price reporter. The implementation effectively proxies to Binance and automatically converts to the Renegade quote token (USDC).
> price-reporter: Automatic quote conversion for Renegade exchange

- Cargo.lock
- auth/auth-server/src/server/handle_external_match/mod.rs
This PR runs `cargo update` to ingest changes made in `renegade-api` to fix the `get_quote_amount` bug as per https://github.com/renegade-fi/renegade/pull/946. Also removes logs added for debugging.
> auth-server: cargo update to fix get_quote_amt bug, remove logs

- auth/auth-server/src/chain_events/error.rs
- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/chain_events/worker.rs
- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/store/helpers.rs
- auth/auth-server/src/store/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
This PR adds a bundle store so the asynchronous `chain-events` worker can access API level details about a bundle when processing settlement. 
We maintain two in-memory maps:
-  bundle IDs -> bundle contexts
-  nullifier -> bundle IDs
Our workload prioritizes writes from the HTTP handler and only ever has one reader that is not time-sensitive, so we use a Mutex to guarantee atomic writes (over something like a RwLock). While this does mean all operations are serialized, the nature of our workload means we are okay with reads queuing up behind writes.
We remove bundle contexts on `NullifierSpent` to prevent unbounded memory growth. By indexing nullifier -> bundle_id, each cleanup holds the lock for at most O(M) (M = `MAX_CONCURRENT_TASKS`) instead of O(N).
> auth-server: add bundle store

- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/handle_external_match/settlement.rs
- auth/auth-server/src/store/mod.rs
This PR fixes bundle ID generation to factor in gas sponsorship, since the `chain-events` worker will derive the bundle ID from amounts net of gas sponsorship, the HTTP handler should too (unless the refund is in native ETH). This bundle ID is now used as the `request_id`.
We also write to the bundle store as early as possible to ensure post-settlement tasks can occur.
> auth-server: handle gas sponsorship when deriving bundle id

- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/chain_events/mod.rs
- auth/auth-server/src/chain_events/tasks.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/store/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
This PR migrates settlement metrics recording from the HTTP handler to the async `chain-events` worker.
> auth-server: migrate post settlement metric recording to chain events

- Cargo.lock
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/rpc_shim.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR introduces the `rpc_shim` module to the funds manager's `CustodyClient`, which is responsible for handling a subset of RPC method calls with opinionated validation logic. This lets us use the funds manager as a custom RPC "transport" to implement [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193)-compatible clients in libraries such as [Viem](https://viem.sh/docs/clients/transports/custom).
Our concrete use case for this is to sign `eth_signTypedData_v4` requests generated when interacting with our Hyperliquid account from a keypair custodied in Fireblocks, while applying application-specific validation logic to the incoming requests, such as: "do we really want to deposit this much into Hyperliquid?"
> funds-manager: custody_client: init rpc_shim w/ eth_accounts impl

- auth/auth-server/src/chain_events/error.rs
- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/chain_events/tasks.rs
- auth/auth-server/src/chain_events/worker.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
This PR migrates gas sponsorship metrics recording and rate limiting logic to the `chain-events` listener. It also deletes unused code, namely the polling method of awaiting nullifiers from the previous implementation.
> auth-server: migrate gas sponsorship to listener task

- Cargo.lock
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/custody_client/deposit.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/rpc_shim.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/error.rs
- funds-manager/funds-manager-server/src/server.rs
This PR implements EIP-712 typed data signing with the Fireblocks Hyperliquid vault. Due to the incompatibility of the current Fireblocks Rust SDK version with the current Fireblocks API, this PR includes a major version upgrade of the Fireblocks Rust SDK. This results in some updating of other code paths invoking the Fireblocks Rust SDK.
These tests should cover all code paths which interact with the `custody_client.fireblocks_client`.
> funds-manager: custody_client: upgrade fireblocks sdk, implement typed data signing

- auth/auth-server/src/chain_events/tasks.rs
- auth/auth-server/src/telemetry/helpers.rs
This PR ensures we increment the "number of external match requests" counter when an external match is requested (previously was incrementing when we observed a settlement nullifier). It also removes erroneous recording of `EXTERNAL_MATCH_SETTLED_BASE_VOLUME`. These bugs were introduced in the recent migration to a chain events worker.
> auth-server: metrics: record req counter in correct ctx

- funds-manager/funds-manager-server/src/custody_client/deposit.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/rpc_shim.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
This PR implements withdrawing from the Hyperliquid vault to the Hyperliquid account, i.e. bridging from Fireblocks to Hyperliquid.
> funds-manager: custody_client: implement withdrawing to hyperliquid from vault

- Cargo.lock
- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/chain_events/tasks.rs
- auth/auth-server/src/chain_events/worker.rs
- auth/auth-server/src/helpers.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/contract_interaction.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/refund_calculation.rs
- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/server/handle_external_match/settlement.rs
- auth/auth-server/src/server/order_book/mod.rs
- auth/auth-server/src/store/helpers.rs
- auth/auth-server/src/store/mod.rs
This PR adds a handler for malleable matches to the auth server. This implementation largely follows the implementation of the standard assembly endpoint. 
- Add post-bundle metrics and store bundle in `BundleStore`
> auth-server: handle-external-match: Add malleable match handler

- Cargo.lock
- auth/auth-server/Cargo.toml
- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/helpers.rs
- auth/auth-server/src/server/gas_estimation/constants.rs
- auth/auth-server/src/server/gas_estimation/gas_cost_sampler.rs
- auth/auth-server/src/server/gas_estimation/mod.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/contract_interaction.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/refund_calculation.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/quote_comparison/handler.rs
- auth/auth-server/src/telemetry/sources/mod.rs
This PR migrates the auth server from using `ethers` to `alloy`.
> auth-server: Migrate from `ethers` to `alloy`

- auth/auth-server/src/server/handle_external_match/gas_sponsorship/mod.rs
This PR sets the `data` field on the settlement transactions rather than the `input` field to match the client configurations.
> auth-server: Use `data` field on tx

- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/metrics/mod.rs
This PR refactors the `metrics` module of the `funds-manager-server` crate to use `alloy` and the `DarkpoolClient` accordingly.
> funds-manager: metrics: use alloy & DarkpoolClient

- Cargo.lock
- Cargo.toml
- auth/auth-server/Cargo.toml
- funds-manager/funds-manager-api/Cargo.toml
- funds-manager/funds-manager-api/src/lib.rs
- funds-manager/funds-manager-api/src/serialization.rs
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-api/src/types/venue.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/metrics/mod.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
- funds-manager/funds-manager-server/src/server.rs
- price-reporter/Cargo.toml
This PR begins migrating the `funds-manager` crates to using `alloy` and the new `DarkpoolClient` as opposed to `ethers` and the old `ArbitrumClient`. In this PR, we migrate the `funds-manager-api` crate and some top-level modules of the `funds-manager-server` crate.
This is part of a larger effort to migrate the entire extensions repo to `alloy` and the `DarkpoolClient`.
The `funds-manager`, `auth`, and `price-reporter` crates are not expected to build until this refactor is complete.
> funds-manager: api, server: begin migration to alloy

- funds-manager/funds-manager-server/src/fee_indexer/fee_balances.rs
- funds-manager/funds-manager-server/src/fee_indexer/index_fees.rs
- funds-manager/funds-manager-server/src/fee_indexer/mod.rs
- funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
This PR upgrades the `fee_indexer` module of the `funds-manager-server` crate to use `alloy` instead of `ethers`, and use the new `DarkpoolClient` helpers from the relayer repo.
> funds-manager-server: fee_indexer: use alloy & darkpoolclient

- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/labels.rs
This PR adds a counter metric that is incremented every time the relayer cannot produce a quote for a given quote request.
> auth-server: handle_external_match: record metric for # quotes not found

- auth/auth-server/Cargo.toml
- auth/auth-server/src/chain_events/error.rs
- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/error.rs
- auth/auth-server/src/helpers.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/gas_estimation/gas_cost_sampler.rs
- auth/auth-server/src/server/handle_external_match/gas_sponsorship/contract_interaction.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/quote_comparison/handler.rs
This PR updates the `auth-server` crate to properly use the new `DarkpoolClient` exported from the relayer crates.
> auth-server: use DarkpoolClient

- Cargo.lock
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/middleware.rs
This PR fixes the funds manager's auth stack in the following 2 ways:
1. We use the raw query string for v2 auth. Previously, query parameters were liable to getting reordered when parsing into a `HashMap`
2. We discard the query string for v1 auth, as it is not expected there
> funds-manager-server: use original query for v2 auth, no query for v1 auth

- Cargo.lock
- Cargo.toml
- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/rpc_shim.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/fee_indexer/mod.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/server.rs
This PR updates the config pattern for the funds manager to parse chain-specific configuration parameters from a JSON file. This file can either be fetched from S3 at runtime, or provided locally (for easier local development).
Using these chain-specific configurations, we instantiate the various funds manager clients separately per-chain.
Basically all of the logic for these clients is chain-specific, and any chain-agnostic logic is cheap to replicate, making this a significantly simpler approach than splitting these clients into chain-agnostic and chain-specific constituents.
For example, while the `CustodyClient` does interact with a single, global DB, 1) pretty much every table will have a `chain` column along which to segment interaction, and 2) we use a DB pool anyway, so there is …
> funds-manager-server: cli: create chain-specific clients from config file

- auth/auth-server/src/server/handle_external_match/mod.rs
- auth/auth-server/src/telemetry/labels.rs
- auth/auth-server/src/telemetry/mod.rs
This PR changes the auth server logic to record a fill ratio of zero in the case that a quote isn't found.
> auth-server: telemetry: Record zero fill ratio for no quote

- funds-manager/funds-manager-server/src/main.rs
This PR adds back the old, chain-unspecified routes for backwards compatibility, routing them to invoke handlers for the Arbitrum chain by default
> funds-manager-server: add backwards-compatibility routes defaulting to arb chain

- .gitignore
- Cargo.lock
- Cargo.toml
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/rpc_shim.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/fee_indexer/mod.rs
- funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/middleware.rs
- funds-manager/funds-manager-server/src/mux_darkpool_client.rs
- funds-manager/funds-manager-server/src/server.rs
This PR has the funds manager's routes/handlers accept a `Chain` path parameter where relevant. This is in expectation of the `Chain` enum specifying `ArbitrumSepolia, ArbitrumOne, BaseSepolia, BaseMainnet` more directly than just `Mainnet, Testnet`. For this reason we also introduce an `Environment` enum that the server must be configured with, which will be used in e.g. the Hyperliquid functionality to select `Chain::ArbitrumSepolia, Chain::ArbitrumOne` as appropriate.
> funds-manager-server: handlers: include chain path param where relevant

- Cargo.lock
- price-reporter/Cargo.toml
- price-reporter/src/http_server/routes.rs
- price-reporter/src/main.rs
- price-reporter/src/pair_info.rs
- price-reporter/src/utils.rs
- price-reporter/src/ws_server.rs
This PR ensures price streams are deduplicated by ticker in the global `SharedPriceStreams`, but deduplicated by price topic in client-facing subscription maps.
> price-reporter: deduplicate prices streams by ticker

- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/db/models.rs
- funds-manager/funds-manager-server/src/db/schema.rs
- funds-manager/funds-manager-server/src/fee_indexer/index_fees.rs
- funds-manager/funds-manager-server/src/fee_indexer/queries.rs
- funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/migrations/2025-05-15-010726_chain_columns/down.sql
- funds-manager/migrations/2025-05-15-010726_chain_columns/up.sql
This PR adds a `chain` column to all of the tables in the DB, backfilling all existing rows to set it to `arbitrum` and updating the queries appropriately.
Note that we use environment-agnostic chain names for this column, i.e. `arbitrum` and `base` as opposed to `arbitrum-sepolia`, `arbitrum-one`, `base-sepolia`, `base-mainnet`.
Since we already use separate DBs per environment, this captures all the necessary information, and makes the migration simpler (the same `up.sql` can be applied both to the testnet and mainnet DBs).
> funds-manager-server: db: add `chain` columns

- Cargo.lock
- price-reporter/Cargo.toml
- price-reporter/src/http_server.rs
- price-reporter/src/http_server/routes.rs
- price-reporter/src/main.rs
- price-reporter/src/pair_info.rs
- price-reporter/src/utils.rs
- price-reporter/src/ws_server.rs
This PR allows specifying multiple chains when spinning up the price reporter. It removes the remap file path arg, opting instead to retrieve remaps from the default remote location.
> price-reporter: use multiple remaps

- Cargo.lock
- Cargo.toml
- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/helpers.rs
- auth/auth-server/src/main.rs
- price-reporter/src/utils.rs
This PR bumps `alloy` to `v1.0.1` in relayer extensions (funds manager changes in different PR).
> auth-server: bump alloy

- Cargo.lock
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
- funds-manager/funds-manager-server/src/server.rs
This PR ensures that we invoke chain-specific static methods on the `Token` struct, now that the funds manager is initializing multiple token remaps.
Unfortunately, all of these code paths are only hit on a mainnet deployment: either because they are part of the execution quote generation / settlement API, or in the case of withdrawals to hyperliquid, we only construct the USDC token on mainnet (HL has its own testnet USDC that we hardcode in the testnet case).
As such, testing will be deferred until a mainnet deployment is out. Still, I have confirmed that a testnet funds manager can run when configured with both arbitrum-sepolia and base-sepolia configs.
> funds-manager-server: use chain-aware token methods

- Cargo.lock
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/custody_client/deposit.rs
- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
- funds-manager/funds-manager-server/src/custody_client/gas_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/db/models.rs
- funds-manager/funds-manager-server/src/fee_indexer/queries.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
- funds-manager/funds-manager-server/src/server.rs
- funds-manager/migrations/2025-05-15-174324_per_chain_vaults/down.sql
- funds-manager/migrations/2025-05-15-174324_per_chain_vaults/up.sql
This PR updates the funds manager to expect & use chain-specific vault names. Accordingly, I have created a database migration that renames the `vault` column values in the `hot_wallets` table to include the "Arbitrum " prefix (as currently all vaults are Arbitrum vaults).
I have also updated the names of the vaults in our testnet Fireblocks workspace.
> funds-manager-server: use chain-specific vault names

- Cargo.lock
- price-reporter/src/main.rs
- price-reporter/src/pair_info.rs
- price-reporter/src/utils.rs
This PR fixes bugs found while testing loading multiple token remaps:
- cannot rely on `default_chain()` since there are multiple
- improper usage of `derivative` crate leading to duplicate price streams 
- couldn't find tokens because we weren't lowecasing
> price-reporter: fix multi-chain stream init

- price-reporter/src/pair_info.rs
This PR avoids a panic given a price topic made of addresses of tokens on two different chains.
> price-reporter: prevent panic on ticker unwrap

- price-reporter/src/ws_server.rs
This PR fixes prices requested using the `renegade` exchange.
Previously, we were replacing the exchange but not the quote ticker before establishing a connection. This meant we were establishing connections for "binance-BASE-USDC" instead of "binance-BASE-USDT" and returning prices for those tokens with a BASE / USDC market on Binance (11/17 of our tokens). The prices would be wrong since the conversion would technically not be necessary (they're already in units of USDC / BASE).
> price-reporter: fix renegade topic handling

- price-reporter/src/utils.rs
- price-reporter/src/ws_server.rs
This PR ensures we properly check if a price stream required quote conversion.
Previously, we were checking after mutating the exchange to be Binance, causing `requires_quote_conversion` to always return `false` since `Binance !== Renegade`.
We also fix the actual quote conversion: we receive USDT / USDC from Binance, meaning we should divide the main price by this conversion price to get USDC / BASE.
> price-reporter: fix requires_quote_conversion

- Cargo.lock
- price-reporter/src/utils/canonical_exchange.rs
- price-reporter/src/utils/mod.rs
This PR adds the ability to read canonical exchanges from token remaps provided using a file path.
> price-reporter: read canonical exchange from file path

- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_malleable_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/direct_match.rs
- auth/auth-server/src/server/api_handlers/external_match/mod.rs
- auth/auth-server/src/server/api_handlers/external_match/quote.rs
- auth/auth-server/src/server/api_handlers/mod.rs
- auth/auth-server/src/server/api_handlers/order_book.rs
- auth/auth-server/src/server/gas_sponsorship/mod.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/rate_limiter/gas_sponsorship_rate_limiter.rs
- auth/auth-server/src/server/rate_limiter/mod.rs
This PR makes the following changes to the endpoint handlers in the external match flow:
- Moves each handler to its own file for clarity
- Defines a `RequestContext` and `ResponseContext` type that will be used for pre and post-processing of the request.
- Uses this type throughout the quote endpoint's post-processing metrics.
- Use this request context type for other external match endpoints
> auth-server: server: external-match: Use contexts in quote handler

- auth/auth-server/src/telemetry/mod.rs
This PR fixes the metrics naming prefix for the auth server; `renegade_relayer` -> `auth-server`.
> auth-server: telemetry: Fix metrics prefix for datadog

- price-reporter-client/src/lib.rs
- price-reporter-client/src/price_stream.rs
This PR modifies the price reporter client that the auth server and funds manager use to use the renegade topic when streaming prices, ensuring they retrieve the authoritative price.
> price-reporter-client: use canonical exchange

- price-reporter/src/main.rs
- price-reporter/src/utils/mod.rs
- price-reporter/src/utils/pair_info.rs
- price-reporter/src/ws_server.rs
This PR ensures that when a price is requested of a token that exists on multiple token lists, we find the right pair. 
Previously we used the `Token` on the default chain which would error when a pair that existed on a non-default chain was requested.
> price-reporter: allow same token on multiple remaps to be found

- price-reporter/src/utils/mod.rs
- price-reporter/src/utils/pair_info.rs
This PR adds a helper to find a token pair that exists on the same chain. This ensures PairInfo can be parsed from incoming price topics in a multi-chain price reporter where neither base nor quote token are guaranteed to be unique to a chain.
> price-reporter: add token pair resolution

- Cargo.lock
- Cargo.toml
- auth/auth-server/Cargo.toml
- auth/auth-server/src/server/gas_sponsorship/contract_interaction/arbitrum.rs
- auth/auth-server/src/server/gas_sponsorship/contract_interaction/base.rs
- auth/auth-server/src/server/gas_sponsorship/contract_interaction/mod.rs
- auth/auth-server/src/server/helpers.rs
This PR adds a `base` submodule to the gas sponsorships module with the correct base gas sponsorship implementation. The differences between the base implementation and the arbitrum implementation are:
- The base gas sponsor authority (auth server), signs the abi encoded tuple `(nonce, refundAddress, refundAmount)`, whereas the arbitrum implementation manually serializes these values.
- The base gas sponsor ABI has slightly different function names.
- The base darkpool contract does not have separate methods for an external match and an external match with receiver specified. Instead it uses `address(0)` to encode `msg.sender` as the match recipient.
- Deferred until the auth server builds for base
> auth-server: gas-sponsorship: Add Base gas sponsorship implementation

- Cargo.lock
- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/error.rs
- auth/auth-server/src/server/api_handlers/settlement.rs
- auth/auth-server/src/server/gas_sponsorship/contract_interaction/arbitrum.rs
- auth/auth-server/src/telemetry/abi_helpers/arbitrum.rs
- auth/auth-server/src/telemetry/abi_helpers/base.rs
- auth/auth-server/src/telemetry/abi_helpers/mod.rs
- auth/auth-server/src/telemetry/helpers.rs
- auth/auth-server/src/telemetry/mod.rs
This PR factors the chain-dependent functionality out of the telemetry module into a submodule `abi_helpers`. This is specifically the logic to parse nullifiers from chain-specific calldata.
- Gas estimation module fails on base with the current implementation.
> auth-server: telemetry: abi_helpers: Add chain-specific ABI helpers

- auth/auth-server/src/chain_events/tasks.rs
- auth/auth-server/src/server/gas_estimation/constants.rs
- auth/auth-server/src/server/gas_estimation/gas_cost_sampler.rs
- auth/auth-server/src/server/gas_estimation/gas_oracles/arbitrum.rs
- auth/auth-server/src/server/gas_estimation/gas_oracles/base.rs
- auth/auth-server/src/server/gas_estimation/gas_oracles/mod.rs
- auth/auth-server/src/server/gas_estimation/mod.rs
- auth/auth-server/src/server/helpers.rs
- auth/auth-server/src/telemetry/sources/mod.rs
This PR sets up gas estimation for Base. I generalized the existing Arbitrum implementation into a `gas_oracles` module which is feature flagged.
> auth-server: gas-estimation: Add base gas estimation

- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/error.rs
- funds-manager/funds-manager-server/src/helpers.rs
This PR makes a couple tweaks to the `/withdraw-to-hyperliquid` code paths in order to smooth out `Insufficient funds` errors we see in Fireblocks when trying to transfer from the HL vault to the bridge:
1. We round up the requested withdrawal amount (and the derived transfer amount from the quoter hot wallet, if necessary) to the nearest 6th decimal place (USDC decimals). This is to obviate any f64 precision issues due to requested withdrawal amount w/ higher precision than 6 decimal places.
2. For ERC20 transfers, we wait 3 confirmations - this is the [default # of confirmations](https://support.fireblocks.io/hc/en-us/articles/10883496786204-Default-Deposit-Control-and-Confirmation-Policy) used by Fireblocks for contract calls, and could explain why even after transferring from the hot …
> funds-manager: custody_client: withdraw: round HL transfer amounts, wait 3 confs

- deploy/deploy-config.toml
- funds-manager/funds-manager-api/src/types/mod.rs
- funds-manager/funds-manager-api/src/types/vaults.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/rpc_shim.rs
- funds-manager/funds-manager-server/src/custody_client/vaults.rs
- funds-manager/funds-manager-server/src/custody_client/withdraw.rs
- funds-manager/funds-manager-server/src/error.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds a `/custody/get-vault-balances` endpoint to the funds manager. This will be used to account for vault holdings in our NAV metrics.
> funds-manager: server: add get-vault-balances endpoint

- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
- funds-manager/funds-manager-server/src/custody_client/gas_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/error.rs
- funds-manager/funds-manager-server/src/fee_indexer/index_fees.rs
- funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
This PR makes a quality of life improvement to top-up quoter hot wallet gas (ether) balances before swapping. This is done within a top-up tolerance, set to the default gas wallet top up tolerance of 10%.
I generalized the helpers for gas wallet top ups to allow for this flow.
> funds-manager-server: hot-wallets: Top up quoter wallet gas before swap

- price-reporter-client/src/lib.rs
This PR includes the mint in an error message that we're seeing commonly in the arbitrum one auth server to help debug.
> auth-server: price-reporter-client: Specify token mint in err message

- auth/auth-server/src/bundle_store/helpers.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_malleable_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/mod.rs
- auth/auth-server/src/server/api_handlers/settlement.rs
- auth/auth-server/src/telemetry/abi_helpers/arbitrum.rs
- auth/auth-server/src/telemetry/abi_helpers/base.rs
This PR records malleable match bundles in the bundle store. The bundle ID is generated from the malleable match rather than an external match -- which is not known until the tx is submitted.
- Fetch malleable matches in the on-chain event listener to resolve these bundles.
> auth-server: api-helpers: settlement: Record malleable bundles in store

- Cargo.lock
- auth/auth-server/src/chain_events/abis/arbitrum.rs
- auth/auth-server/src/chain_events/abis/base.rs
- auth/auth-server/src/chain_events/abis/mod.rs
- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/chain_events/mod.rs
- auth/auth-server/src/telemetry/abi_helpers/arbitrum.rs
This PR adds helpers for parsing external matches (malleable or standard) from darkpool calldata. This allows the chain events listener to record settlement metrics for malleable match bundles.
> auth-server: chain-events: abis: Parse external matches from calldata

- auth/auth-server/src/server/api_auth.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_malleable_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/direct_match.rs
- auth/auth-server/src/server/api_handlers/external_match/mod.rs
- auth/auth-server/src/server/api_handlers/external_match/quote.rs
- auth/auth-server/src/server/api_handlers/key_management.rs
- auth/auth-server/src/server/rate_limiter/mod.rs
This PR follows up on #240 to add more in-depth tracing for auth server requests. This will, at a high level, allow us to determine where the bottlenecks are in serving a bundle request. 
I will add more trace spans and fields as need comes.
> auth-server: api-handlers: Add tracing for auth server endpoints

- .github/workflows/clippy.yml
- .github/workflows/test.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- renegade-solver/Cargo.toml
- renegade-solver/README.md
- renegade-solver/src/cli.rs
- renegade-solver/src/error.rs
- renegade-solver/src/main.rs
- renegade-solver/src/uniswapx/api_types.rs
- renegade-solver/src/uniswapx/mod.rs
This PR moves the renegade solver into the relayer extensions monorepo.
> renegade-solver: Move from separate repo

- funds-manager/Dockerfile
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds a `/swap-immediate` route, which fetches & executes a quote without first returning the quote to the client. The client can set desired slippage etc. parameters via the query string.
This PR also configures the funds manager to export OTLP traces and instruments the `get-execution-quote`, `execute-swap`, and `swap-immediate` routes so that we can measure the overal latency improvements due to using the new endpoint.
> funds-manager: api, server: add swap-immediate route

- Cargo.lock
- renegade-solver/Cargo.toml
- renegade-solver/src/uniswapx/api_interaction.rs
- renegade-solver/src/uniswapx/mod.rs
This PR adds a simple LRU cache to deduplicate orders polled from the UniswapX API. We cache the order on its `orderHash` field provided by the API.
> renegade-solver: uniswapx: Cache serviced orders to deduplicate

- Cargo.lock
- renegade-solver/Cargo.toml
- renegade-solver/src/uniswapx/mod.rs
- renegade-solver/src/uniswapx/solve.rs
This PR makes two changes:
- Adds `Address::ZERO` as a stand-in for native ETH swaps to the supported tokens map
- Requires that if one token is USDC in a pair, the other token must be explicitly supported for the pair to be supported. E.g. We cannot fill `TOKENABC -> USDC` if `TOKENABC` is not supported by Renegade.
> renegade-solver: uniswapx: Handle USDC and native ETH

- Cargo.lock
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/execution_client/error.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/middleware.rs
This PR ensures that we search for transfers of the _buy_ mint, rather than the _base_ mint, when finding the actual buy amount in a swap. This was preciously preventing us from recording swap costs on sells.
- Test against mainnet
> funds-manager: metrics: use correct buy mint when searching for transfer logs

- renegade-solver/src/error.rs
- renegade-solver/src/uniswapx/abis/conversion.rs
- renegade-solver/src/uniswapx/abis/mod.rs
- renegade-solver/src/uniswapx/abis/uniswapx.rs
- renegade-solver/src/uniswapx/mod.rs
- renegade-solver/src/uniswapx/solve.rs
- renegade-solver/src/uniswapx/uniswap_api/types.rs
This PR adds UniswapX `PriorityOrderReactor` types to the repo and replaces all uses of the `OrderEntity` with the decoded `PriorityOrder`. The amounts on the `OrderEntity` are incorrect for an unknown reason, so we directly decode the solidity type used to parameterize the order.
> renegade-solver: uniswapx: abis: Add ABI definitions

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-api/src/types/venue.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
This PR logs the "tool" used by LiFi in a quote. We leave tagging metrics with this as a TODO.
> funds-manager: log LiFi tool used in quote

- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/custody_client/vaults.rs
This PR tweaks the `get_vault_balances_handler` to include balances of native assets (e.g. ETH). For simplicity, we assume that any vault whose balances are queried only holds the native asset of one chain, so we simply use the zero address to represent any native asset balances held in the vault.
If we start using cross-chain vaults, we can use a more intelligent "pseudo-addressing" scheme for these balances.
> funds-manager: custody_client: include native assets in vault balances endpoint

- auth/auth-server/src/main.rs
- auth/auth-server/src/server/api_handlers/order_book.rs
This PR adds a proxy endpoint for the `/v0/order_book/depth` endpoint on the relayer which returns book depth for all supported pairs.
> auth-server: api-handlers: order-book: Add "all pairs" order book helper

- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
This PR adds fine grained request tracing to swap requests in the funds manager. This will help us understand and debug the recursive trade execution better.
I also added a small optimization to over-approve ERC20 tokens by a constant amplification factor. This removes the need for sending an approval on _every_ swap.
> funds-manager: execution-client: swap: Add better request tracing

- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
This PR tracks the cumulative gas cost in the swap execution metrics. I only log for now, and don't record the metrics because I want to test this value in mainnet before we start recording real metrics to the NAV dashboard.
> funds-manager: execution_client: swap: Track cumulative gas cost

- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/metrics/labels.rs
This PR makes the following changes:
1. Reports gas cost of swap transactions as a new metric. I confirmed via the log attributes that the computed gas costs were correct.
2. Wraps all on-chain transactions in a retry loop. This will ameliorate nonce issues that happen by virtue of us using different instantiations of an alloy client throughout the funds manager. The nonce middleware will re-fetch in between transaction retries, so no extra work is needed beyond retrying.
>  funds-manager: execution-client: Wrap transactions in retry loop

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
This PR returns execution cost in the API response from the funds manager on the `/swap-immediate` route. This cost represents the USD denominated cost of executing on LiFi versus Binance for the swap.
This will be used in the bot server to enable per-asset execution cost rate limits.
I moved the metrics recorder out of a thread to enable using the swap costs in the hot path. This operation is not latency expensive, and the endpoint in generally does not have stringent latency constraints on it.
> funds-manager: handlers: Return execution cost in `/swap-immediate`

- auth/auth-server/src/bundle_store/mod.rs
- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/chain_events/tasks.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/direct_match.rs
- auth/auth-server/src/server/api_handlers/settlement.rs
- auth/auth-server/src/telemetry/labels.rs
This PR adds metrics recording for the price staleness of a bundle. Price staleness is calculated as the time between time of price sample and the time of settlement. For direct match bundles, which do not have a TimestampedPrice, we approximate by using the time the post-request subroutines are run. 
Metric added is `auth_server.external_match_price_staleness` in milliseconds.
> auth-server: record price staleness metric

- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/metrics/labels.rs
- funds-manager/funds-manager-server/src/metrics/mod.rs
This PR makes a couple misc tweaks to swap cost recording in the funds manager:
1. We _attempt_ to decode all ERC20 logs as transfers, rather than _assuming_ they all are, skipping over non-transfer logs
2. We tag swap cost metrics with the (env-agnostic) chain on which they occurred
> funds-manager: metrics: handle non-transfer logs & add chain tag

- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/rate_limiter/execution_cost_rate_limiter.rs
- auth/auth-server/src/server/rate_limiter/mod.rs
- auth/auth-server/src/server/setup.rs
This PR adds a Redis-based execution cost rate limiter to the auth server. This rate limiter will read from the redis cluster written to by the bot server when it reports its execution costs.
Notably we don't fail the API execution if the rate limit check fails, we emit a warning for now. I will change this later if we see fit, but I'm planning to test this with live rate limits before changing routing behavior.
Routing decisions will come in a follow-up.
> auth-server: setup: Create execution cost rate limiter

- Cargo.lock
- Cargo.toml
- auth/auth-server/Cargo.toml
- auth/auth-server/src/http_utils.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/api_auth.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_malleable_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/direct_match.rs
- auth/auth-server/src/server/api_handlers/external_match/quote.rs
- auth/auth-server/src/server/api_handlers/mod.rs
- auth/auth-server/src/server/mod.rs
- auth/auth-server/src/server/rate_limiter/mod.rs
This PR adds logic in the pre-request handlers for each of the external match endpoints to check the execution rate limit for the pair they're matching. For now, if the rate limit is exceeded, the auth server will just log a warning. In a follow-up I'll add routing logic that places orders in the global pool after rate limits are exceeded.
> auth-server: api-handlers: Check execution rate limits before forwarding

- auth/auth-server/src/error.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/direct_match.rs
- auth/auth-server/src/server/api_handlers/external_match/mod.rs
- auth/auth-server/src/server/api_handlers/external_match/quote.rs
- auth/auth-server/src/server/api_handlers/mod.rs
This PR adds a rejection handler branch for the `AuthServerError` type and adds a `BadRequest` variant to this error. We use this error type to return HTTP 400 when an address is not in the token mapping. 
Previously the auth server would return an opaque "500: Internal Server Error" because the `AuthServerError` type was not handled.
> auth-server: Handle bad request errors properly

- auth/auth-server/diesel.toml
- auth/auth-server/migrations/2025-07-01-210135_add_whitelist_flag/down.sql
- auth/auth-server/migrations/2025-07-01-210135_add_whitelist_flag/up.sql
- auth/auth-server/src/server/db/models.rs
- auth/auth-server/src/server/db/schema.rs
This PR adds a `rate_limit_whitelisted` column to the `api_keys` table. This will let us selectively bypass execution swap cost rate limits on a per-key basis.
> migrations: Add whitelisted column to `api_keys` table

- auth/auth-server-api/src/key_management.rs
- auth/auth-server-api/src/lib.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/api_handlers/key_management.rs
- auth/auth-server/src/server/db/models.rs
- auth/auth-server/src/server/db/queries.rs
This PR adds a `GET /api-keys` method which returns all API keys registered to the auth server. This will be used in the admin panel to view API keys and their whitelist status.
> auth-server: api-handlers: Add `GET /api-keys` method

- auth/auth-server/src/error.rs
- auth/auth-server/src/server/api_auth.rs
- auth/auth-server/src/server/api_handlers/external_match/mod.rs
This PR changes the auth server to return http 400 in cases when decoding a request body fails, and extends the mapping of `AuthServerError -> ApiError` to more completely capture all API codes.
> auth-server: api-handlers: Return more complete 400 responses

- Cargo.lock
- auth/auth-server/src/server/setup.rs
- funds-manager/Dockerfile
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/middleware.rs
- funds-manager/funds-manager-server/src/relayer_client.rs
- funds-manager/funds-manager-server/src/server.rs
- price-reporter-client/src/lib.rs
- price-reporter-client/src/price_stream.rs
This PR adds an `exit_on_stale` option to the `PriceReporterClient` which, when set, has the client maintain a 1-minute timer that exits the current process. This timer gets re-created every time a price is updated, so as long as we're receiving prices within each minute, the self-destruct won't be invoked.
> price_reporter_client: optional exit-on-stale

- auth/auth-server/Cargo.toml
- auth/auth-server/src/http_utils/request_response.rs
- auth/auth-server/src/http_utils/stringify_formatter.rs
- auth/auth-server/src/server/api_handlers/external_match/mod.rs
This PR adds a `json_deserialize` method which can optionally convert all stringified numbers into number types ahead of deserialization. This allows clients to send numbers as string values.
> auth-server: api-handlers: Allow stringified numbers in request

- auth/auth-server/src/chain_events/listener.rs
- auth/auth-server/src/chain_events/tasks.rs
- auth/auth-server/src/telemetry/labels.rs
This PR ensures that we record the quoter match spread cost from the perspective of the quoter. The quoter takes the _opposite_ side of the external party's order, and this informs the sign on the spread cost metric.
We also call out an assumption made in the recording of this metric: that the external match for which we record this cost was executed against a quoter. Currently, the overwhelming majority (~all) of our external match volume is against the quoters, and this assumption greatly simplifies the implementation of this metric.
> auth-server: chain_events: record quoter match spread costs from quoter POV

- Cargo.lock
- price-reporter/Cargo.toml
- price-reporter/src/errors.rs
- price-reporter/src/exchanges/error.rs
- price-reporter/src/exchanges/mod.rs
- price-reporter/src/exchanges/util.rs
- price-reporter/src/http_server.rs
- price-reporter/src/http_server/routes.rs
- price-reporter/src/main.rs
- price-reporter/src/utils/mod.rs
- price-reporter/src/utils/pair_info.rs
- price-reporter/src/ws_server.rs
This PR completes the migration off of the `renegade-price-reporter` dependency and gets the price reporter building and streaming on its own internalized logic.
> price-reporter: migrate off of `renegade-price-reporter` dependency

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds a handler & exposes a route for the new `try_swap_into_target_token` method.
Testing will have to be done on mainnet w/ small amounts, and is blocked by client-side implementation of this endpoint in Typescript. Any resultant bugfixes will come in a follow-up PR.
> funds-manager: handlers: add swap-into-target-token handler

- auth/auth-server-api/src/fee_management.rs
- auth/auth-server/src/main.rs
- auth/auth-server/src/server/api_handlers/external_match_fees.rs
- auth/auth-server/src/server/db/queries.rs
This PR adds two endpoints for removing fee overrides: one for per-user and one for per-asset.
> auth-server: api-handlers: Add methods for removing fee overrides

- auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/direct_match.rs
- auth/auth-server/src/server/api_handlers/external_match/mod.rs
- auth/auth-server/src/server/api_handlers/external_match/quote.rs
- auth/auth-server/src/server/db/models.rs
- auth/auth-server/src/server/db/queries.rs
This PR sets the `relayer_fee` field on each request during preprocessing according to the fee override stored in the DB.
> auth-sever: api-handlers: Set relayer fee in request processing

- funds-manager/funds-manager-api/src/types/fees.rs
- funds-manager/funds-manager-server/src/fee_indexer/queries.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/migrations/2025-07-24-192651_fee_redemption_index/down.sql
- funds-manager/migrations/2025-07-24-192651_fee_redemption_index/up.sql
This PR adds a `/get-unredeemed-fee-totals` route to the funds manager, used to get the total amount of unredeemed fees for each mint. These holdings will be added to our view of NAV.
> funds-manager: fee_indexer: route for getting unredeemed fee totals

- Cargo.lock
- renegade-solver/Cargo.toml
- renegade-solver/src/cli.rs
- renegade-solver/src/error.rs
- renegade-solver/src/main.rs
- renegade-solver/src/uniswapx/abis/mod.rs
- renegade-solver/src/uniswapx/abis/priority_order.rs
- renegade-solver/src/uniswapx/fixed_point/error.rs
- renegade-solver/src/uniswapx/fixed_point/mod.rs
- renegade-solver/src/uniswapx/mod.rs
- renegade-solver/src/uniswapx/priority_fee.rs
- renegade-solver/src/uniswapx/renegade_api.rs
- renegade-solver/src/uniswapx/solve.rs
This PR adds priority fee calculation given a PriorityOrder and the canonical Renegade price. 
In the next PR we will scale the requested amounts using the priority fee before requesting an external match from the relayer.
> solver: add priority fee calculation

- Cargo.lock
- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/execution_client/error.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
This PR adds the price impact param to the lifi quote request. We will set this value high for most quotes (30%) to handle $EDGE -- which LiFi does a poor job of pricing. We will instead rely on the slippage parameter to constrain execution costs.
> funds-manager-api: quoters: Add price impact param

- Cargo.lock
- Cargo.toml
- auth/auth-server/src/server/api_handlers/external_match/mod.rs
- auth/auth-server/src/server/api_handlers/mod.rs
This PR checks for the native asset `0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE` in token validation in the auth server. This fixes a bug wherein native ETH was disallowed at the API layer.
> auth-server: api-handlers: Allow native asset in token validation

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
This PR fixes an issue with the price deviation check in which the funds manager was not using the decimal corrected price from the quote.
> funds-manager: execution-client: Use decimal corrected price

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/quotes.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi.rs
- funds-manager/funds-manager-server/src/execution_client/venues/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/quote.rs
- funds-manager/funds-manager-server/src/handlers.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
- funds-manager/funds-manager-server/src/metrics/labels.rs
This PR completes porting over the current execution stack (Lifi-only) to using the new `ExecutionQuote` and `ExecutableQuote` types. This includes some refactoring, notably:
1. I removed the `AugmentedExecutionQuote` type, and moved its helper methods to `ExecutionQuote`. This involved some deduplication of adjacent methods on the old `ExecutionQuote` struct
2. I removed some fields from the `SwapCostData` struct, as they were not relied on in practice, and the fields from which they are computed no longer exist on the new `ExecutionQuote` struct, i.e. are not venue-agnostic.
3. I moved the calculation of `buy_amount_actual` from the `MetricsRecorder` to the `ExecutionClient`. This is largely for ergonomics, since execution venues may expose different ways to determine this amount. For …
> funds-manager: execution_client: use ExecutableQuote for Lifi execution

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
This PR ensures that the `is_sell` method on the `ExecutionQuote` constructs a chain-aware USDC token. The current `Token::usdc()` call assumes the `default_chain`. This results in incorrect swap cost metrics, and also leads to quotes being considered invalid on acount of price deviation, because in sells on the non-default chain, the base token is always assumed to be USDC and have a price of 1.
I will be sure that these changes are reflected appropriately into the `andrew/multi-venue-quote-selection` branch
> funds-manager-api: types: quoters: chain-aware is_sell method

- funds-manager/funds-manager-server/src/execution_client/venues/cowswap/api_types.rs
- funds-manager/funds-manager-server/src/execution_client/venues/cowswap/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/api_types.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs
This PR adds definitions for Cowswap API types involved in getting quotes, creating orders, and querying trades on orders. None of these types are used yet, as such the fields on them may get pared down further as I implement the associated functionality.
> funds-manager: execution_client: venues: cowswap: add API type definitions

- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/quote.rs
This PR ports over the fixes from #327 & #328 so they are not lost when `andrew/multi-venue-quote-selection` is merged.
> funds-manager: execution_client: port over misc fixes

- prover-service/server/src/error.rs
- prover-service/server/src/main.rs
- prover-service/server/src/prover.rs
This PR adds the endpoint handler structure for the prover service. This has one endpoint per proof that will be generated.
- Add auth, we'll use HTTP basic auth for this service
> prover-service: prover: Add endpoint handler structure

- prover-service/server/src/error.rs
- prover-service/server/src/prover.rs
This PR implements the endpoint handlers for the prover service which generate the proofs using the relayer helpers.
- Add proof linking endpoints + request fields
- Will test in tandum with relayer implementation
> prover-service: prover: Implement endpoint handlers

- Cargo.lock
- Cargo.toml
- prover-service/api/src/lib.rs
- prover-service/server/src/main.rs
- prover-service/server/src/prover.rs
This PR adds proof linking types to the request response types of the prover service. This can take two forms:
- Proof linking requests on their own -- used in the `VALID COMMITMENTS` <-> `VALID REBLIND` link
- Proof linking requests piggybacked on Plonk proof requests -- used in all the match circuits.
These patterns mirror those currently used in the relayer to generate proof links.
- Deferred until relayer integration
> prover-service: prover: Add proof linking types to request/response

- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/cowswap/api_types.rs
- funds-manager/funds-manager-server/src/execution_client/venues/cowswap/mod.rs
This PR tweaks the `ExecutionClient` to fetch quotes across venues in parallel. In addition, we make some other misc changes:
1. Decreasing order validity to 2 minutes on Cowswap - no reason to keep orders around much longer after we've timed out waiting for them to experience a trade, but setting a 1 minute expiry is rejected by the Cowswap API on the grounds of being too short.
2. We add a 1-second sleep after submitting an ERC20 approval for a Cowswap quote. Empirically, we frequently see the Cowswap API reject order placements due to us not having approved, despite this being the case. I tried setting a high number of required confirmations on the approval TX, but this seemed to have literally no effect. Using a direct timeout is simpler.
> funds-manager: execution_client: swap: fetch quotes in parallel

- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/cowswap/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs
This PR re-introduces logging of the path invoked when a Lifi request fails. This was not ported over in the process of implementing multi-venue quote selection.
> funds-manager: execution_client: venues: lifi: log errant request path

- funds-manager/funds-manager-server/src/execution_client/venues/cowswap/mod.rs
The TX hash returned by the Cowswap API is a `String` and as such doesn't implement `LowerHex`, I merged this as-is hastily.
> funds-manager: execution_client: cowswap: log tx hash string correctly

- funds-manager/funds-manager-server/src/execution_client/swap.rs
This PR ensures that we log the quoted price before we've selected a tentative best quote.
> funds-manager: execution_client: log price before best quote selected

- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/main.rs
This PR generalizes the "min swap amount" checks into a single one: before fetching a quote for a swap, we compute the expected notional volume using the renegade price, and error early if it is below our threshold.
> funds-manager: execution_client: check expected swap amt before getting quote

- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs
- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/cowswap/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/metrics/mod.rs
This PR makes a couple fixes to mitigate nonce issues in the funds manager:
First, we remove usage of `ProviderBuilder::new().connect_provider(base_provider)`. This was implemented on the incorrect assumption that the fillers with which the `base_provider` was constructed would overwrite the "recommended fillers" introduced in `ProviderBuilder::new()`. 
This is not the case - the fillers in the `base_provider` are completely ignored, which I verified by trying to send transactions from a provider constructed with `ProviderBuilder::default().connect_provider(base_provider)` (no fillers are added in `default`). As such, this means the recommended fillers (notably, the `CachedNonceManager`) were used in the constructed provider.
We now construct an appropriately-configured provider in all …
> funds-manager: helpers: send ERC20 approvals w/ a retry

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/mod.rs
- funds-manager/funds-manager-server/src/metrics/labels.rs
This PR tweaks the `QuoteParams` type to allow clients to optionally specify the venue on which they want to execute the requested swap.
Additionally, we allow the `slippage_tolerance` field to override the configured max price deviation if it is set to a higher value, so that clients can "force through" costly swaps. This is a bit of parameter conflation: `slippage_tolerance` is intended to indicate the tolerance for price impact on each venue, i.e. the deviation between the trade price & the venue midpoint, whereas the price deviation check is between the trade price & the "Renegade" price. Still, this keeps the API simple while allowing for costly swaps in a pinch.
> funds-manager: execution_client: specify venue in API

- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/mod.rs
This PR temporarily disables Cowswap execution until we implement a mechanism for self-trade prevention.
> funds-manager: execution_client: temp disable cowswap

- Cargo.lock
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/execution_client/venues/mod.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
This PR has the funds manager's `MetricsRecorder` gracefully handle the processing of non-`Transfer` logs when calculating self-trade volume.
> funds-manager: metrics: handle non-transfer logs in self trade volume calc

- auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/direct_match.rs
- auth/auth-server/src/server/api_handlers/mod.rs
- auth/auth-server/src/telemetry/labels.rs
This PR tags external match metrics with `shared: true | false` to add widgets displaying the count of shared vs. exclusive bundles that are propagated.
> auth-server: metrics: tag external match metrics with shared

- auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs
- auth/auth-server/src/server/api_handlers/external_match/direct_match.rs
- auth/auth-server/src/server/api_handlers/mod.rs
- auth/auth-server/src/telemetry/labels.rs
This PR tags external match volume with `request_path` so that we can differentiate between flow originating from the quote and assembly path vs. the direct match path.
> auth-server: metrics: tag external match metrics with request_path

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/mod.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
This PR adds a `increase_price_deviation` field to the `QuoteParams` allowing clients to specify whether the funds manager should increase its price deviation tolerance in the case that a quote exceeds it.
> funds-manager: api, execution_client: allow increasing price deviation

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/api_types.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/quote.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
This PR implements the logic of converting a `BebopQuote` into an `ExecutableQuote`. I continued in stripping down the API type definitions along the way.
> funds-manager: execution_client: bebop: convert into ExecutableQuote

- funds-manager/funds-manager-api/src/types/quoters.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/swap.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/api_types.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/quote.rs
- funds-manager/funds-manager-server/src/helpers.rs
- funds-manager/funds-manager-server/src/main.rs
- funds-manager/funds-manager-server/src/metrics/cost.rs
This PR implements `ExecutionVenue::get_quote` for the `BebopClient`. In the process, I simplified many of the API types. There were a bunch of issues stemming from using untagged enums & the combination of flattened structs w/ `f64`s that are now avoided.
> funds-manager: execution_client: bebop: get quotes

- funds-manager/funds-manager-server/src/cli.rs
- funds-manager/funds-manager-server/src/execution_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/api_types.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/mod.rs
This PR configures the funds manager to use an API key for Bebop.
> funds-manager: venues: bebop: add API key

- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
This PR ensures the refill endpoint includes USDC when checking for refill status by swapping `get_all_base_tokens` for `get_all_tokens`.
> funds-manager: custody-client: include usdc in refill check

- funds-manager/funds-manager-server/src/custody_client/gas_sponsor.rs
This PR excludes USD from the refill check since it would attempt to read the zero address and fail.
> funds-manager: custody-client: exclude usd in refill check

- auth/auth-server/src/chain_events/tasks.rs
This PR removes the computation of the remaining value & time on the gas sponsorship rate limit bucket, accidentally reintroduced when merging the previous PR.
> auth-server: chain_events: remove reintroduced sponsorship rate limit tags

- auth/auth-server/src/bundle_store/helpers.rs
This PR ensures that we include the match direction in the preimage of the hash used as the bundle's ID. We have seen a bug in prod wherein a buy-side match result witnessed onchain was associated with a sell-side bundle stored in the auth server, because the match amounts lined up.
This led to us assuming that the _quote-denominated_ `refund_amount` on the fetched bundle was the amount of _base token_ used to sponsor the settled match. Due to the difference in fixed-point precision (and price) of the base and quote tokens, this led to an immensely inflated refund value being recorded.
> auth-server: bundle_store: include match direction in bundle ID

- funds-manager/funds-manager-server/src/custody_client/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs
- funds-manager/funds-manager-server/src/helpers.rs
This PR bumps the default # of confirmations to await the settlement of transaction from 1 -> 2. The reason we do this is to avoid operating on preconfirmed state due to the enablement of flashblocks in Base mainnet + Alchemy.
With the enablement of flashblocks, the `eth_getTransactionReceipt` RPC will [by default return transaction receipts included in flashblocks](https://docs.base.org/base-chain/flashblocks/apps#eth-gettransactionreceipt). This is the RPC relied upon by `alloy` downstream of invoking `pending_tx.get_receipt()`, in [`watch_pending_transaction`](https://github.com/alloy-rs/alloy/blob/v1.0.1/crates/provider/src/provider/trait.rs#L1287). In that same method, you can see that if `required_confirmations <= 1`, the receipt is returned as soon as it is found onchain - in the …
> funds-manager: wait 2 tx confirmations by default

- renegade-solver/Cargo.toml
- renegade-solver/src/uniswapx/abis/priority_order.rs
- renegade-solver/src/uniswapx/renegade_api.rs
- renegade-solver/src/uniswapx/solve.rs
This PR enables the solver to handle orders with multiple output entries, as long as they are the same token. This is fairly trivial as the `Executor` must simply maintain the invariant that it holds sufficient output tokens by the time `reactorCallback` is finished. The `Reactor` contract is responsible for actually transferring these output tokens from the `Executor` to recipient(s).
> solver: fill orders with multiple outputs

- renegade-solver/src/error.rs
- renegade-solver/src/uniswapx/abis/conversion.rs
- renegade-solver/src/uniswapx/executor_client/contract_interaction.rs
- renegade-solver/src/uniswapx/executor_client/errors.rs
- renegade-solver/src/uniswapx/executor_client/mod.rs
- renegade-solver/src/uniswapx/solve.rs
- renegade-solver/src/uniswapx/uniswap_api/types.rs
This PR adds helpers to submit a solution to the executor contract, including computing the total `gasPrice` net of `priorityFee` and `basePriorityFee`.
In the next PR I will add tx simulation for testing.
> solver: add settlement helpers

- Cargo.lock
- renegade-solver/src/fee_cache/fees.rs
- renegade-solver/src/fee_cache/mod.rs
- renegade-solver/src/fee_cache/worker.rs
This PR adds a base fee cache that is updated on every L2 block. We do this to remove retrieval of the latest base fee from the hot path of building a tx.
> solver: add base fee cache

- funds-manager/funds-manager-server/src/execution_client/venues/bebop/api_types.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/api_types.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs
This PR bypasses the gas limit estimate returned by the Lifi & Bebop APIs in favor of local gas estimation. This is primarily so that we catch reverts during estimation instead of executing a reverting transaction.
> funds-manager: execution_client: bebop, lifi: fallback to gas estimation

- Cargo.lock
- renegade-solver/Cargo.toml
- renegade-solver/src/cli.rs
- renegade-solver/src/flashblocks/listener.rs
- renegade-solver/src/flashblocks/mod.rs
- renegade-solver/src/flashblocks/multi_listener.rs
- renegade-solver/src/flashblocks/types.rs
This PR adds a `FlashblocksListener` that will enable the solver to subscribe to and receive events from the configured Flashblocks block builder.
Much of the code is taken directly from https://github.com/base/node-reth, we could have added the crate as a dependency but I chose to copy specific files over instead since it 3x'd the overall number of dependencies.
> solver: add flashblocks listener

- Cargo.lock
- renegade-solver/Cargo.toml
- renegade-solver/src/tx_store/error.rs
- renegade-solver/src/tx_store/mod.rs
- renegade-solver/src/tx_store/store.rs
This PR adds the TxStore which will sit between the solver, `tx_driver` (to be added), and `chain_events_listener` (to be added). This store will hold transactions ready to be submitted along with their schedules. It references the base fee cache so that transactions are read with the latest base fee populated.
> solver: add tx store for queued txns and their statuses

- renegade-solver/src/tx_driver/driver.rs
- renegade-solver/src/tx_driver/error.rs
- renegade-solver/src/tx_driver/mod.rs
- renegade-solver/src/tx_store/store.rs
This PR adds the `TxDriver`, a module that reads transactions and schedules from the `TxStore` and fires them based on their trigger definitions.
> solver: add tx driver

- renegade-solver/src/chain_events/listener.rs
- renegade-solver/src/chain_events/mod.rs
This PR adds a ChainEventsListener which listens for transaction inclusion events from the flashblocks block builder and updates the TxStore to mark these transactions as seen.
> solver: add chain events listener

- renegade-solver/src/planner/mod.rs
- renegade-solver/src/tx_store/store.rs
This PR adds logic to compute the trigger `L2Position` as well as a buffer given measurements of the system, to be used by the TxDriver to submit transactions such that they are included in the target `L2Position`. Essentially, the computation is as follows: 
1. Count the number of whole flashblock windows to step back from the target flashblock to account for submission latency
2. Account for any intra-flashblock buffer needed for more accuracy
3. Construct and return a `SendPlan`
> solver: planner: add logic to compute trigger L2Position and buffer

- funds-manager/funds-manager-server/src/execution_client/swap/swap_immediate.rs
- funds-manager/funds-manager-server/src/execution_client/venues/bebop/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/cowswap/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs
- funds-manager/funds-manager-server/src/execution_client/venues/mod.rs
This PR adds an `excluded_quote_sources` parameter to the `ExecutionVenue::get_quotes` method, and tracks the sources of failing quotes in the `swap_immediate` loop. Now, whenever we fail to execute a quote from a given source, we then skip fetching new quotes from that source on subsequent retries, unless the swap size is decreased.
> funds-manager: execution_client: venues: exclude failing quote sources from retries

- Cargo.lock
- funds-manager/funds-manager-server/Cargo.toml
- funds-manager/funds-manager-server/src/fee_indexer/index_fees.rs
- funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
This PR fixes fee indexing & redemption on Base. We previously were only parsing notes according to the Arbitrum fee settlement ABI, despite listening for the appropriate `NotePosted` event on both chains. We also ensure the inclusion of redemption TXs in full Base blocks.
> funds_manager: fee_indexer: Base fee indexing + redemption

- renegade-solver/src/cli.rs
- renegade-solver/src/error.rs
- renegade-solver/src/fee_cache/fees.rs
- renegade-solver/src/fee_cache/worker.rs
- renegade-solver/src/tx_driver/driver.rs
- renegade-solver/src/tx_store/store.rs
- renegade-solver/src/uniswapx/executor_client/errors.rs
- renegade-solver/src/uniswapx/executor_client/mod.rs
- renegade-solver/src/uniswapx/mod.rs
- renegade-solver/src/uniswapx/solve.rs
This PR modifies the solver to store a ready-to-send tx in the TxStore, such that when the time to submit a tx arrives there is no work to be done except submission. The benefits of this are two-fold:
- hot path of tx submission is optimized
- we know the tx hash before submission ensuring we record confirmation. Previously, there was a race between the sequencer and the flashblocks listener as sometimes the sequencer would be slow to respond with the tx hash, resulting in inclusion in a flashblock being missed.
> solver: build tx before awaiting send

- renegade-solver/src/arrival_control/controller.rs
- renegade-solver/src/arrival_control/ema.rs
This PR adds an arrival controller that estimates one-way delay via EMA and computes send time as `target_ts - delay_ms`.
> solver: add arrival control module

- renegade-solver/src/arrival_control/controller.rs
- renegade-solver/src/flashblocks/clock/ema.rs
- renegade-solver/src/flashblocks/clock/mod.rs
This PR adds the FlashblockClock which is reponsible for converting a (flashblock index, L2 block index) into a timestamp (ms since epoch). This timestamp is used as the target timestamp used by the arrival controller. It estimates flashblock and L2 block durations using EMAs and uses them to estimate when a future flashblock will be seen over the WebSocket.
> solver: add flashblock clock

- price-reporter-client/src/lib.rs
In this PR, we update the `PriceReporterClient` (used by both the funds manager & the auth server) to fetch the actual USDT price instead of returning a hardcoded `1.0`.
> price-reporter-client: get actual USDT price

- Cargo.lock
- Cargo.toml
- funds-manager/funds-manager-server/src/helpers.rs
In this PR, we upgrade our `alloy` dependencies to version [`1.0.32`](https://github.com/alloy-rs/alloy/releases/tag/v1.0.32) so that we can ingest the fix in https://github.com/alloy-rs/alloy/pull/2851, allowing us to remove our manual TX confirmation waiter.
> funds-manager: helpers: remove manual confirmation waiter

- auth/auth-server/src/server/setup.rs
- funds-manager/funds-manager-server/src/server.rs
- price-reporter-client/src/lib.rs
- renegade-solver/src/main.rs
In this PR, we add a `stream_prices` flag to the `PriceReporterClient` constructor, allowing the client to be constructed w/o initializing the `MultiPriceStream`. Additionally, we set the websocket URL scheme to be `wss` or `ws` depending on if the base URL uses `https` or `http`.
> price-reporter-client: optionally stream prices, set ws/wss accordingly

- funds-manager/funds-manager-api/src/types/gas.rs
- funds-manager/funds-manager-server/src/db/models.rs
- funds-manager/funds-manager-server/src/handlers/gas.rs
This PR adds extra information about gas wallets in the `GET /custody/:chain/gas-wallets` endpoint, specifically:
- The current status (`active`, `inactive`, `pending`) of the wallet
- The peer to which the wallet is currently allocated
This will help us view gas wallets in the toolbox.
> funds-manager: Include gas wallet info in api response

- funds-manager/funds-manager-api/src/types/gas.rs
- funds-manager/funds-manager-server/src/custody_client/queries.rs
- funds-manager/funds-manager-server/src/error.rs
- funds-manager/funds-manager-server/src/handlers/gas.rs
- funds-manager/funds-manager-server/src/main.rs
This PR adds a `/custody/{chain}/gas-wallets/set-gas-wallet-status` route which allows an admin to manually override the status of a gas wallet. This will be used in the `rtool` CLI.
> funds-manager-server: Add `set-gas-wallet-status` route
