renegade-fi/relayer-extensions

funds-manager/funds-manager-server/src/fee_indexer/index_fees.rs, funds-manager/funds-manager-server/src/fee_indexer/queries.rs, funds-manager/funds-manager-server/src/fee_indexer/redeem_fees.rs
This PR fixes a few bugs with fee indexing and redemption ahead of the fee custody management implementation.
- Tested the bugfixes locally
=> funds-manager: fee-redemption: Fix misc bugs with fee redemption

funds-manager/funds-manager-api/src/lib.rs, funds-manager/funds-manager-server/src/custody_client/hot_wallets.rs, funds-manager/funds-manager-server/src/custody_client/mod.rs, funds-manager/funds-manager-server/src/custody_client/queries.rs, funds-manager/funds-manager-server/src/handlers.rs, funds-manager/funds-manager-server/src/main.rs
This PR implements an endpoint to withdraw from fireblocks to a hot wallet backing the specified vault.
- Tested the endpoint withdrawing from the quoters vault
=> funds-manager: endpoint to withdraw from fireblocks to hot wallet

Cargo.lock, price-reporter/Dockerfile
This PR fixes up a few directory and build issues with the `price-reporter` dockerfile after we moved it into the `realyer-extensions` repo. 
- Built and deployed the mainnet price reporter
=> price-reporter: Dockerfile: Fixup & standardize Dockerfile

funds-manager/funds-manager-server/src/handlers.rs
This PR enforces an upper bound the amount that can be withdrawn from the funds manager. This is to protect against any unforeseen errant behavior from the quoters. This value is currently hardcoded to $50k.
=> funds-manager-server: set max allowable withdrawal value

auth-server/Dockerfile, auth-server/src/main.rs
This PR adds a Dockerfile to the auth server for deployment. It is templated off of the funds manager dockerfile with appropriate values changed
- Built and deployed
=> auth-server: Dockerfile: Add dockerfile

Cargo.lock, auth/auth-server/src/main.rs, auth/auth-server/src/server/handle_external_match.rs
This PR adds support for the quote and assemble-quote endpoints through the auth server.
=> auth-server: Support new quote and assemble endpoints

auth/auth-server/src/telemetry/helpers.rs
This PR fixes the issue where metrics were recording amounts calculated from non-decimal corrected prices
=> auth-server: use decimal corrected price

auth/auth-server/src/server/handle_external_match.rs
This PR adds attributes to bundle logging for more bundle information.
=> auth-server: add order attributes to bundle logs

auth/auth-server/src/server/handle_external_match.rs, auth/auth-server/src/telemetry/helpers.rs
This PR bubbles up label creation for labels that are applied to all metrics of a request (e.g. request ID and key description). This ensures request ID can be used to link metrics + logs together since the same one is used. To this end, request ID is added as an attribute to bundle logs.
=> auth-server: centralize label creation

auth/auth-server/src/server/mod.rs, auth/auth-server/src/telemetry/sources/mod.rs, auth/auth-server/src/telemetry/sources/odos/mod.rs, auth/auth-server/src/telemetry/sources/odos/types.rs
This PR fixes clippy issues in odos module.
=> auth-server: Fix clippy issues in odos module

auth/auth-server/src/server/handle_external_match.rs
This PR adds key description to the list of attributes to log for bundles. It also ensures bundles are logged before awaiting for settlement.
=> auth-server: Add key desc to bundle log attributes

Cargo.lock, auth/auth-server/src/server/handle_external_match.rs
This PR handles the case where bundles in the quote + assemly flow are updated. We record metrics using the updated bundle, and we log the update.
=> auth-server: Handle updated bundles

funds-manager/funds-manager-server/src/execution_client/swap.rs
This PR explicitly sets the TX fee for swap transactions executed by the funds manager
Tested by running a local funds manager & successfully executing swaps
=> funds-manager: execution_client: swap: set swap tx fee

auth/auth-server/src/server/handle_external_match/mod.rs
This PR adds tags for the user & endpoint in the quote request, assembly, & direct external match logging handlers
=> auth-server: handle_external_match: add user, endpoint tags to logs

auth/auth-server/src/server/handle_external_match/mod.rs
This PR decorates the `Non-200 response from relayer` log with additional debugging information, including the requesting client, the request path, the request body, and the response body.
=> auth-server: handle_external_match: improve unsuccessful relayer request log

auth/auth-server/src/server/handle_external_match/mod.rs
This PR tweaks the logic in the quote assembly endpoint to prioritize gas sponsorship params set in the query string. This is for proper backwards compatibility. Existing client code utilizing the quote-assemble flow will now request gas sponsorship during the quote stage by default, using the default params. If that code then e.g. sets a `refund_address` when assembling, it would be ignored due to the resubmitted gas sponsorship info from the quote.
=> auth-server: handle_external_match: prefer sponsorship in query params for assembly

funds-manager/funds-manager-server/src/custody_client/withdraw.rs
This PR ensures that we use Hyperliquid's [dummy USDC token](https://sepolia.arbiscan.io/address/0x1baabb04529d43a73232b713c0fe471f7c7334d5) in testnet as opposed to our own USDC token in the token mapping.
This was tested by running a funds manager locally and triggering a withdrawal to hyperliquid
=> funds-manager: custody-client: use HL dummy USDC in testnet

funds-manager/funds-manager-api/src/types/quoters.rs, funds-manager/funds-manager-api/src/types/venue.rs
This PR adds the `buy_amount_min` field to the quote response.
=> funds-manager: quote: add min recv field

auth/auth-server/src/server/handle_external_match/mod.rs, auth/auth-server/src/server/redis_queries.rs
This PR configures gas sponsorship entries in Redis to be expired after `MAX_QUOTE_AGE`ms. The entries would be useless after this duration as the quotes w/ which they're associated become invalid. This is a clean way to keep our Redis storage footprint small.
=> auth-server: redis_queries: expire sponsorship entries

funds-manager/funds-manager-api/src/types/quoters.rs, funds-manager/funds-manager-server/src/metrics/cost.rs
This PR adds logging of swap metadata for more observability.
=> funds-manager: metrics: log swap metadatax

funds-manager/funds-manager-server/src/metrics/cost.rs
This PR ensures values in the executed swap log are decimal corrected.
=> funds-manager: swap: adjust formatting

auth/auth-server/src/server/handle_external_match/mod.rs
This PR adds debug logging to track an intermittent issue where `requested_quote_amount` is 0 for Buy orders despite having non-zero `response_quote_amount` and `base_fill_ratio`.
The logging will help identify:
1. Which calculation step produces the zero value
2. Whether we're hitting the exact quote output branch
3. If the price calculation for Buy orders is correct
This will allow comparison of successful vs failed cases to pinpoint the root cause.
=> auth-server: add debug logs to identify error in calculating req quote amount

Cargo.lock, auth/auth-server/src/main.rs, auth/auth-server/src/server/handle_external_match/mod.rs, auth/auth-server/src/server/mod.rs, auth/auth-server/src/server/rate_limiter/mod.rs
This PR breaks out a separate rate limit for shared bundles, with a default value of 50/min.
=> auth-server: rate-limiter: Add shared bundle rate limits

funds-manager/funds-manager-server/src/custody_client/withdraw.rs
This PR ensures that we account for any existing USDC balance in the Hyperliquid keypair (on Aribtrum) when transferring money from the funds manager to Hyperliquid.
=> funds-manager: custody_client: withdraw: check HL acct bal before transferring

Cargo.lock, auth/auth-server-api/Cargo.toml, auth/auth-server/Cargo.toml, auth/auth-server/src/server/handle_external_match/gas_sponsorship/contract_interaction.rs, auth/auth-server/src/server/helpers.rs, auth/auth-server/src/telemetry/helpers.rs, funds-manager/funds-manager-server/Cargo.toml
This PR bumps `alloy` dependencies to the version pinned in the relayer.
=> auth-server: bump alloy dep

auth/auth-server/src/chain_events/listener.rs, auth/auth-server/src/chain_events/tasks.rs, auth/auth-server/src/chain_events/worker.rs, auth/auth-server/src/main.rs, auth/auth-server/src/server/handle_external_match/mod.rs, auth/auth-server/src/server/handle_external_match/settlement.rs, auth/auth-server/src/server/mod.rs, auth/auth-server/src/store/mod.rs
This PR adds rate limit adjustment to the `chain-events` listener.
=> auth-server: increase rate limit on settlement

auth/auth-server/src/chain_events/listener.rs
This PR changes the auth server's chain events listener to log an error instead of crashing if it fails to process a nullifier.
=> auth-server: chain-events: Do not crash when processing nullifier

price-reporter/src/main.rs, price-reporter/src/utils.rs
This PR initializes prices streams for default tickers without using `Token`, for simplicity.
=> price-reporter: init default tickers

Cargo.lock, Cargo.toml, price-reporter/src/http_server/routes.rs, price-reporter/src/main.rs, price-reporter/src/utils/canonical_exchange.rs, price-reporter/src/utils/mod.rs, price-reporter/src/utils/pair_info.rs, price-reporter/src/ws_server.rs
This PR ensures prices requested for the Renegade topic are routed to the canonical exchange and converted to be quoted in USDC.
Tested locally
=> price-reporter: alias Renegade to canonical exchange

Cargo.lock, auth/auth-server/src/server/gas_sponsorship/contract_interaction.rs
This PR adds `quote_amount` arguments to the ABI definitions and use for darkpool and gas sponsorship malleable match selectors.
=> auth-server: gas-sponsorship: Update malleable match ABIs with `quote_amount`

auth/auth-server/src/bundle_store/mod.rs, auth/auth-server/src/chain_events/listener.rs, auth/auth-server/src/chain_events/tasks.rs, auth/auth-server/src/server/api_handlers/external_match/assemble_malleable_quote.rs, auth/auth-server/src/server/api_handlers/external_match/assemble_quote.rs, auth/auth-server/src/server/api_handlers/external_match/direct_match.rs, auth/auth-server/src/server/api_handlers/external_match/mod.rs, auth/auth-server/src/server/api_handlers/settlement.rs, auth/auth-server/src/telemetry/labels.rs
This PR adds metrics recording for time of price sample -> time of assembly -> time of settlement.
=> auth-server: record price -> assemble -> settle delay metrics

funds-manager/funds-manager-server/src/execution_client/swap.rs, funds-manager/funds-manager-server/src/handlers.rs
This PR makes some miscellaneous tweaks to the new `/swap-into-target-token` endpoint. Namely, we make sure to exclude the dummy "USD" token injected into the token mapping from the set of swap candidates, and we gracefully handle the case where a recursive swap is too small, allowing the remaining swap candidates to be processed instead of erroring out early.
Tested by running a local funds manager w/ mainnet params, hooked up to a local admin panel. Traded small amounts on Base mainnet, asserting the following cases were handled appropriately:
=> funds-manager: execution_client: swap: fix swap candidate predicate & small swap handling

renegade-solver/src/cli.rs, renegade-solver/src/main.rs, renegade-solver/src/uniswapx/executor_client/mod.rs, renegade-solver/src/uniswapx/mod.rs
This PR adds instantiation of an `ExecutorClient` from CLI args, along with accompanying changes to CLI and `UniswapXSolver` structs.
- deferred until ExecutorContract is deployed
=> solver: init executor client

Cargo.lock, renegade-solver/Cargo.toml, renegade-solver/src/cli.rs, renegade-solver/src/main.rs, renegade-solver/src/uniswapx/mod.rs
This PR adds the Price Reporter Client to the solver.
=> solver: add price reporter client

funds-manager/funds-manager-server/src/execution_client/quotes.rs
This PR logs the LiFi request URL when the API returns an error. I'll use this to get a reproducible example of lifi param validation errors.
=> funds-manager: execution-client: Add URL to error logging

funds-manager/funds-manager-api/src/types/quoters.rs, funds-manager/funds-manager-server/src/execution_client/mod.rs, funds-manager/funds-manager-server/src/execution_client/swap.rs, funds-manager/funds-manager-server/src/execution_client/venues/cowswap/abi.rs, funds-manager/funds-manager-server/src/execution_client/venues/cowswap/api_types.rs, funds-manager/funds-manager-server/src/execution_client/venues/cowswap/mod.rs, funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs, funds-manager/funds-manager-server/src/execution_client/venues/mod.rs, funds-manager/funds-manager-server/src/execution_client/venues/quote.rs, funds-manager/funds-manager-server/src/helpers.rs
This PR implements the execution of Cowswap quotes.
=> funds-manager: execution_client: venues: cowswap: execute Cowswap quotes

Cargo.lock, funds-manager/funds-manager-api/src/types/quoters.rs, funds-manager/funds-manager-server/src/execution_client/mod.rs, funds-manager/funds-manager-server/src/execution_client/swap.rs, funds-manager/funds-manager-server/src/execution_client/venues/cowswap/abi.rs, funds-manager/funds-manager-server/src/execution_client/venues/cowswap/api_types.rs, funds-manager/funds-manager-server/src/execution_client/venues/cowswap/mod.rs, funds-manager/funds-manager-server/src/execution_client/venues/lifi/mod.rs, funds-manager/funds-manager-server/src/execution_client/venues/mod.rs, funds-manager/funds-manager-server/src/execution_client/venues/quote.rs, funds-manager/funds-manager-server/src/helpers.rs
This PR begins the implementation of `ExecutionVenue` for the `CowswapClient`, beginning with the `get_quote` method.
=> funds-manager: execution_client: venues: cowswap: get cowswap quote

Cargo.lock, Cargo.toml, auth/auth-server/src/server/mod.rs, prover-service/server/Cargo.toml, prover-service/server/src/main.rs, prover-service/server/src/middleware.rs
This PR ingests propagated spans in the prover service and opens handler spans as a child of these spans.
=> prover-service: Ingest propagated OTEL spans

Cargo.lock
This PR updates `renegade-config` to pull in changes from https://github.com/renegade-fi/renegade/pull/1097
=> price-reporter: update Cargo.lock

renegade-solver/src/uniswapx/abis/priority_order.rs, renegade-solver/src/uniswapx/priority_fee.rs, renegade-solver/src/uniswapx/solve.rs
This PR fixes a bug where the `is_sell` method was returning the inverse. Also adds helpful logging for debug phase.
=> solver: fix flipped side bug, add logging

renegade-solver/src/uniswapx/executor_client/contract_interaction.rs, renegade-solver/src/uniswapx/executor_client/mod.rs, renegade-solver/src/uniswapx/mod.rs
This PR makes changes to the existing ExecutorClient, specifically:
- exposes function to build a TransactionRequest (without maxFeePerGas set)
- exposes a function to send a TransactionRequest (with maxFeePerGas set using base_fee from FeeCache)
- only use WebSocket connection for now
=> solver: prepare executor client for new role

auth/auth-server/src/server/api_handlers/rfqt/helpers.rs, auth/auth-server/src/server/api_handlers/rfqt/quote.rs
This PR ensures transformations from RFQ requests respect the `partialFillAllowed` as well as uses `exact_*_output` methods where appropriate (when `makerAmount` is set, since this is the `receive` amount).
=> auth-server: rfqt: quote: parameterize using correct amount properties
